### ISSUE TITLE
Feature request: Don't add 'Cache-Control' request header by configuration.

### ISSUE THREAD

**Issue by jedie** [requests-cache/requests-cache#1014]
### Use case
I would like to create requests without the `Cache-Control` headers.

### Workarounds
I see no work-a-round, because `requests_cache.policy.directives.set_request_headers()` will be always called and will always the `Cache-Control` header :( (except ugly monkey-patch)

### Plan to implement
Yes

EDIT: Discovered that sending `DO_NOT_CACHE` cause my real problem, because `0x0D0E0200020704` results in a very high `max-age` and the M$ server doesn't like it ;(

**Comment by JWCook** [comment]
I see. I can probably fix this without adding another configuration option. `DO_NOT_CACHE` was intended more as an internal sentinel value than something to send in request headers. I'll try to get that fixed soon.

**Comment by JWCook** [comment]
Sorry for the delay! I got a bit stuck on this one for awhile. Fixes are now in `main`, though.
