### ISSUE TITLE
Support for niquests

### ISSUE THREAD

**Issue by glensc** [requests-cache/requests-cache#1022]
The [niquests] project has caught my attention lately, mostly due API compatibility with `requests` and support for async code.

[niquests]: [niquests](https://github.com/jawah/niquests)

Since my project entrypoint is not really `requests`, but `requests-cache` `CachedSession`, I'm wondering how I could use `niquests` underneath rather `requests`.

**Comment by glensc** [comment]
I looked briefly maybe [CachedSession] constructor can take session object, but it's using inheritance rather composition, so it's likely not possible to do without refactoring requests cache basics?

[1]: https://github.com/requests-cache/requests-cache/blob/855d1d20f65f1331dbe73770964c971e37f40462/requests_cache/session.py#L354

https://en.wikipedia.org/wiki/Composition_over_inheritance

**Comment by glensc** [comment]
But, I found they have it documented:
- https://niquests.readthedocs.io/en/latest/community/recommended.html#requests-cache

**Comment by JWCook** [comment]
Looks like you already found the answer! For this and other similar cases, [CacheMixin](https://requests-cache.readthedocs.io/en/stable/modules/requests_cache.session.html#requests_cache.session.CacheMixin) exists to let you use cooperative inheritance with other custom `Session` classes.
