### ISSUE TITLE
only_if_cached + stale_if_error not working "offline" with more recent library dependencies

### ISSUE THREAD

**Issue by castedo** [requests-cache/requests-cache#1025]
Something fishy is happening with the ["offline mode" described in the docs](https://requests-cache.readthedocs.io/en/stable/user_guide/expiration.html#cache-only-requests).

I see it working as I understand it with more stable dependencies (CentOS 9), but then not working as expected with newer dependencies (Fedora 40). In both cases I'm using `requests_cache` 1.2.1.

I have a nice clean repo case at https://gitlab.com/castedo/not_only_if_cached.

## Steps to repo
```
git clone https://gitlab.com/castedo/not_only_if_cached.git
cd not_only_if_cached
./test-with-centos9-offline.sh
./test-with-centos9-online.sh
./test-with-fedora40-offline.sh
./test-with-fedora40-online.sh
```
## Got

```
requests.__version__='2.25.1'
requests_cache.__version__='1.2.1'
resp.status_code=200
requests.__version__='2.25.1'
requests_cache.__version__='1.2.1'
resp.status_code=200
requests.__version__='2.31.0'
requests_cache.__version__='1.2.1'
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1060, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.12/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f72e4ecb9b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 801, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /search/commits?q=hash%3A1ca488e4d3f33059a04656f855ba22ef5393298a (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f72e4ecb9b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/./get_only_if_cached.py", line 25, in <module>
    resp = session.get(
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests_cache/session.py", line 127, in get
    return self.request('GET', url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests_cache/session.py", line 183, in request
    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests_cache/session.py", line 230, in send
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests_cache/session.py", line 254, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /search/commits?q=hash%3A1ca488e4d3f33059a04656f855ba22ef5393298a (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f72e4ecb9b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
requests.__version__='2.31.0'
requests_cache.__version__='1.2.1'
resp.status_code=200
 cache/d68ef4288b0d316a.json | 184 ++++++++++++++++++++++----------------------
 1 file changed, 92 insertions(+), 92 deletions(-)
```

The two tests on CentOS 9 worked as expected. The cached file did not change and there was no network usage.
But the third test, on Fedora 40, without a network, failed because the network was used.
And then on the fourth, when there is a network, the cached file got changed, as indicated by `git diff`.

## Expected

For all cases to behave the same, no network access, and for the cached file to be left unchanged.

```
requests.__version__='2.25.1'
requests_cache.__version__='1.2.1'
resp.status_code=200
requests.__version__='2.25.1'
requests_cache.__version__='1.2.1'
resp.status_code=200
requests.__version__='2.25.1'
requests_cache.__version__='1.2.1'
resp.status_code=200
requests.__version__='2.25.1'
requests_cache.__version__='1.2.1'
resp.status_code=200
```

**Comment by castedo** [comment]
BTW, those test helper scripts run`podman` but you can probably change or alias it to `docker` and it will still work. If you want to see repo cases on Ubuntu or Debian images let me know.

**Comment by castedo** [comment]
And the Containerfiles (Dockerfiles) for those two images can be found at:
https://gitlab.com/ellerman/nest/dev (Fedora 40 with tons of extra stuff)
and
https://gitlab.com/perm.pub/dock/hidos-dev/-/tree/main/centos-9 (CentOS 9 with some extra stuff)

**Comment by JWCook** [comment]
Thanks for the thorough bug report. I can't immediately tell what the problem is, but it looks like you've given enough details to figure it out. I should be able to get to this later this week.

Meanwhile, if you or anyone else out there has time to help narrow down which specific dependency change(s) are causing this, the help would be appreciated!

**Comment by castedo** [comment]
Glad to help this awesome package. I discovered and started using it just a few days ago. I'm glad I didn't start re-inventing the wheel.

I've updated the test helper script to output more package dependency versions. Unfortunately, I have little clue what might causing this so I'm kind of stabbing in the dark for what packages to compare.

Here's  the output when I ran it on a gianomous Ubuntu 24.04 (Noble) container that I'm using.
```
requests.__version__='2.31.0'
requests_cache.__version__='1.2.1'
version('attrs')='23.2.0'
version('cattrs')='22.2.0'
version('urllib3')='2.0.7'
version('url_normalize')='1.4.3'
resp.status_code=200
```
So interesting that this doesn't seem to have to do with requests 2.31.0 because it's working fine on Ubuntu.

I'll test more more Fedora image variations this week and report back what happens.

**Comment by castedo** [comment]
I've got a great isolation of the issue. It has something to do with brotli. Installing the Python brotli Fedora package causes this problem. I'm going to try and confirm on some smaller and cleaner images and will post the details here (pointing to the repo).

**Comment by castedo** [comment]
@JWCook I think I've got I nice clean repo case saved for you at:

https://gitlab.com/castedo/not_only_if_cached/-/blob/03831502c6e452a93dd9794a723a56ee9a62efd7/README.txt

That README.txt is the starting point. Definitely seems like something weird, confusing, and not ideal is happening with some kind of brotli package interaction. I'll leave the rest for you. Let me know if you want anymore help.

**Comment by castedo** [comment]
I've found a quick fix:
```
session.get(
    ...
    headers = {
        ...
         "Accept-Encoding": "gzip, deflate",
        ...
    }
)
```

Forcing the "Accept-Encoding" setting in the headers I'm guessing prevents some downstream software from checking to see if brotli is available, then deciding the change the request from what is in the cache, and thus cause online request and not use the cache.

I'm not sure if this is something `requests-cache` should prevent from happening. Maybe this is something `requests-cache` should allow to happen. Nonetheless, it's very confusing to have cache behavior change only because a compression library becomes available.

**Comment by alessio-locatelli** [comment]
@castedo Is the problem reproducible only for that `url` + `query` + `headers`? Or the request parameters can be simplified while still reproducing the problem? I am asking because that Github URL returns 422 response status code, not 200.

**Comment by alessio-locatelli** [comment]
### Step by step

1. `requests-cache` calls `Session.request()` method of the `requests` lirbary
2. then the traceback travels back to the `requests-cache` (`Cachedsession.send()` method), etc.
3. `requests` calls `make_headers` [source](https://github.com/psf/requests/blob/main/src/requests/utils.py#L70)
4. `make_headers` calls `ACCEPT_ENCODING += ",br"` [source](https://github.com/urllib3/urllib3/blob/8b2474d32b57f096a815ab52f9b54a843d68c140/src/urllib3/util/request.py#L30C5-L30C29)

Without `brotli` we have: `'accept-encoding=deflate, gzip'`

With `brotli` we have: `'accept-encoding=br, deflate, gzip'`.

A cached request is invalidated due to the different headers. 

Since the cache request has been invalidated, the library is trying to make a new request, and, obviously, fails if you are offline.

### Conclusion

I understand that this can be confusing, but a library cannot guarantee portability across all possible different environment (with/without Brotli, with other different dependencies or system packages, etc.).   

The best we can do is mention in the README that installing/uninstalling Brotli may invalidate the cache.   
@JWCook Does this make sense?

**Comment by castedo** [comment]
Yep, that makes sense. Seems like the only change worth making it a change to documentation. I can do a PR if that makes sense.

Two areas for the docs that come to mind are:

1. https://requests-cache.readthedocs.io/en/stable/user_guide/expiration.html#cache-only-requests
2. https://requests-cache.readthedocs.io/en/stable/user_guide/matching.html#selective-parameter-matching

For the 1. maybe it's worth adding a caveat that cached request identification is not solely dependent on the parameters to `session.get`, but also involves how `CachedSession` is configured and how `requests`/`urllib3` modify/prepare the request headers after the `session.get`.

In the area of the documentation of 2. it might be worth mentioning that request parameters can sometimes be "forced to be fixed" by passing them, and an example would be the work around I mention above of always passing `"Accept-Encoding": "gzip, deflate"` so that one of those other layers does not tweak it.

Thoughts?

**Comment by alessio-locatelli** [comment]
> I can do a PR if that makes sense.

> Two areas for the docs that come to mind are:

Yes, what you say sounds even better than I expected. A pull request with the above noted would be great.

**Comment by castedo** [comment]
@alessio-locatelli #1037 is a PR to resolve this issue.
