### ISSUE TITLE
Using `decode_content` parameter in a CachedSession gets overrided by the next CachedSession created

### ISSUE THREAD

**Issue by FernandoKGA** [requests-cache/requests-cache#1026]
### The problem
When using two CachedSession objects, that are for different purposes and one of them should have the `decode_content` parameter disabled, it is affecting the other CachedSession object that isn't related.

![Screenshot from 2024-10-31 00-26-34](https://github.com/user-attachments/assets/80166424-e077-46bf-b9f0-9d369b8b6057)

### Expected behavior
The `decode_content` parameter should be independent for each session.

### Steps to reproduce the behavior
The `cache_options` object is the configuration for the CachedSession, it must has the backend as `"backend": "filesystem"`. The `cache_name` is just the path where it's going so save the files. 

```py
self.session = CachedSession(
    cache_name,
    **cache_options,
    decode_content=False,
 )

 session = CachedSession(
    cache_name,
    **cache_options,
)
```

### Workarounds
Use `decode_content=False` in both sessions. But it isn't the desired outcome.

### Environment
- requests-cache version: 1.2.1
- Python version: 3.10.14
- Platform: Ubuntu 24.04.1 LTS

**Comment by FernandoKGA** [comment]
From my research into the source code. The `json_serializer` is being reused as the same object, causing the overriding. It should create a **new serializer** everytime.

**Comment by JWCook** [comment]
Okay, I see the problem. Thanks for the bug report.

I can fix this, but out of curiosity, what is the use case for multiple session objects with different `decode_content` settings?

**Comment by FernandoKGA** [comment]
I was preparing a fix already, but couldn't finish on time. :(

The use case: we are using each session for a different base URL, one of them is an file storage, which we don't want the data to be decoded. The other is a web API.

**Comment by JWCook** [comment]
Done! This will be included in the next release. Meanwhile, you can test the changes in `main`, and I can publish a pre-release package if needed.

**Comment by FernandoKGA** [comment]
Thanks for the quick fix!

I will test it first thing tomorrow.
