### ISSUE TITLE
MongoDB backend: 'Cannot use MongoClient after close' when making consecutive requests without a session

### ISSUE THREAD

**Issue by manu-mtld** [requests-cache/requests-cache#1034]
### The problem
When using the MongoDB backend, consecutive `requests.get()` calls result in the following error:
`pymongo.errors.InvalidOperation: Cannot use MongoClient after close`

### Expected behavior
Consecutive requests.get() calls should work without requiring a requests.Session.

### Steps to reproduce the behavior
Here’s a minimal example that reproduces the issue:
```
import requests_cache
import requests

requests_cache.install_cache('request_cache', backend='mongodb')

# First request succeeds
requests.get('https://github.com')

# Second request fails
requests.get('https://github.com')
```

### Workarounds
1. Using the default SQLite backend works as expected.
2. Using a `requests.Session` also avoids the issue:
```
import requests_cache
import requests

requests_cache.install_cache('request_cache', backend='mongodb')

session = requests.Session()
session.get('https://github.com')
session.get('https://github.com')
```
However, some API wrapper libraries (e.g., those that internally use requests) don’t allow explicit session handling, making this workaround impractical.

### Environment
- requests-cache version: 1.2.1
- Python version: 3.12
- Platform: MacOS

**Comment by JWCook** [comment]
Thanks for the bug report. I think I see the problem:
1. With `install_cache()` + `requests.get()`, `requests` will implicitly create a new session for each request
2. After the request, `requests` will close the session
3. When the parent `requests.Session` closes, `requests-cache` also closes any backend connections
4. `install_cache()` will reuse existing backend cache objects (including connections) across requests
5. The MongoDB backend doesn't automatically reopen closed connections

I think the best general fix for this is to add an `autoclose` parameter for all backends that can disable step 3 above. I added something similar over in the related library [aiohttp-client-cache](https://github.com/requests-cache/aiohttp-client-cache). I can have that default that to `False` when using `install_cache()`.

> some API wrapper libraries (e.g., those that internally use requests) don’t allow explicit session handling

There are sometimes library-specific ways to handle that ([some examples here](https://requests-cache.readthedocs.io/en/stable/user_guide/compatibility.html)). If you point me to the specific library you want to add caching to, I can check if there's a way to inject a `CachedSession` object or other workaround.

**Comment by JWCook** [comment]
Fixed in `main`.
