### ISSUE TITLE
invalidate single responses

### ISSUE THREAD

**Issue by girst** [requests-cache/requests-cache#156]
Hi, I'm working with an API that might return a "come back later" response (code 200). I need to cache "final" responses for a long time, but "come back later" ones only for a short time. Something like this would be ideal:

```python
r = request.get("http://example.test/expensive-api-call?foo=id")
if r.text == "come back later": # obviously, a little bit more involved
    r.invalidate_cache()  # either invalidate cache for this url only, or ...
    r.set_cache_timeout(10)  # set cache duration to 10 seconds, for the next request to this url only
# ...
```

**Comment by JWCook** [comment]
This is an interesting use case. There are several other requests for setting different expire times before sending a request (see issue #108, PR #177), but setting the expiration after the request is a new one.

Implementing that as a method on the response object would be rather complicated. Off the top of my head, the easiest way to implement this would be to add a method on the session, say `CachedSession.update_expiration(method, url, expires_after, params=None)`. That would take all the same parameters used for your original request, which are needed to re-create the correct cache key (using `BaseCache.create_key()`). It would grab response with that key from the cache, and update its expiration time. Usage would then look like:
```python
session = CachedSession()
response = session.get("http://example.test/expensive-api-call?foo=id")
if come_back_later(response):
    session.set_cache_timeout('GET', "http://example.test/expensive-api-call?foo=id", 10)
```

I think this would be made easier after PR #177 is complete (which will store expiration time for each individual request).

@girst Would you or someone else be interested in putting together a PR for this?

**Comment by girst** [comment]
On Sun, Feb 28, 2021 at 08:17:51AM -0800, Jordan Cook wrote:
>@girst Would you or someone else be interested in putting together a PR 
>for this?

sorry, i completely forgot about this ticket :), otherwise i'd reported 
back with the following earlier.

i don't actually need that feature any longer, as the api i'm working 
with stopped this 200-come-back-later nonsense.

for a while, i was just removing keys immediately like this:

session = CachedSession()
response = session.get("http://example.test/expensive-api-call?foo=id")
if come_back_later(response):
     from requests_cache import get_cache
     cache = get_cache()
     main_key = cache.create_key(response.request)
     cache.delete(main_key)

**Comment by JWCook** [comment]
Okay, thanks for the update!
