### ISSUE TITLE
🚀 Upcoming 1.0 release

### ISSUE THREAD

**Issue by JWCook** [requests-cache/requests-cache#402]
requests-cache has been around since 2012, but still has `0.x` version numbers. I think it would be reasonable to finally give this a major version bump to 1.0 sometime in the near future, so I'm making this issue to track what that should ideally include. Please comment if anyone else has thoughts on this.

A beta build is available for testing on PyPI, which can be installed with:
```
pip install -U --pre requests-cache
```

# Features
**Update:** See a complete list of changes [here](https://github.com/requests-cache/requests-cache/blob/main/HISTORY.md#100-unreleased). Feedback would be appreciated!

## General Project Stuff
- Thorough documentation for both users and developers
- Thorough test coverage with both unit tests and backend integration tests

## Stable API
After a 1.0 release, I would like to aim for maintaining backwards-compatibility for all existing features until another major version bump, consistent with semantic versioning. So if there are any backwards-incompatible changes needed to support a new feature, now would be the time to do it!

## (Mostly) complete HTTP header-based caching
- [The most important headers are now supported](https://requests-cache.readthedocs.io/en/latest/user_guide/headers.html), including a subset of `Cache-Control` directives, `ETag`, and others.
- Additional headers and behaviors that are the most likely to be useful have been added under the [cache-control](https://github.com/reclosedev/requests-cache/issues?q=is%3Aissue+label%3Acache-control) issue label.
- Some behaviors specified by [RFC 7234](https://datatracker.ietf.org/doc/html/rfc7234) and related RFCs might add significant complexity to this library without adding much value for users, so I do not plan on implementing some of these unless a solid use case for them comes up.

## Efficient TTL/cache eviction
- For some use cases, `remove_expired_responses()` is sufficient for cleaning up the cache.
- In a high-traffic production environment, keeping the cache size down can be important, and the performance of `remove_expired_responses()` can be a major pain point.
- TTL integration for the backends that natively support it (Redis, MongoDB, and DynamoDB) would be a big improvement.
- This is also important for SQLite, since it's the default backend, and some users accumulate very large caches with it. This can be improved with some modified serialization, indexing, and moving more of the logic from python to SQL.

**Comment by JWCook** [comment]
Update: I was originally planning on another minor release (0.10), but since I'm getting fairly close to finishing all the features outlined above, this will likely turn into the 1.0 release.

I am tentatively planning on making a 1.0.0-beta release sometime this summer, hopefully get some feedback and help hunting for bugs, and then make the stable release within a month or so.

**Comment by ssbarnea** [comment]
I am more than happy to see this library maturing and I am wondering if it would not also be a good idea to move it under `https://github.com/psf` org, so it will be closer to requests. The reason I am asking this is because I am worried about maintenance risks, especially as we know about few hiccups that we faced with other libraries.

I also observed that the library is not yet packaged by all major linux distros, maybe the v1 would motivate them to do it.

**Comment by JWCook** [comment]
@ssbarnea Funny you should mention that, I was was just discussing with reclosedev about transferring this to an org. We were planning to just create a new one. Transfering to the PSF org hadn't occurred to me. What are the criteria for them to adopt a project?

**Comment by ssbarnea** [comment]
Not sure about psf, but we can look about it. There are also other orgs that can help. Creating new org should happen only if we do not find an existing one suitable.

**Comment by JWCook** [comment]
From: https://www.python.org/psf/github:

> Repositories may be transferred to the @psf organization under the following criteria:
> * The repository is relevant to the Python ecosystem at large and has broad interest among the community, or is of critical nature to a Python Software Foundation maintained project such as PyPI.
> * The project has an existing team of at least three maintainers
> * The code is licensed under an [OSI-approved license](https://opensource.org/licenses/alphabetical)
> * The project agrees to operate under the [Python Community Code of Conduct](https://www.python.org/psf/codeofconduct/)

I think all of those points except #2 apply, since I'm currently the only maintainer.

If you're mainly concerned about gaps in maintenance, i.e. if I were to disappear and issues and PRs started piling up, the project is currently on [Code Shelter](https://www.codeshelter.co/). They would be able to give someone else collaborator access if needed.

**Comment by ssbarnea** [comment]
Looks for jazzband or pycontribs orgs, both will accept it. I have projects under both,... note: i created pycontribs years ago, it is less organised/structured than jazzband. Any of them would suit this project well.

I know few other good ones but they have limited scope and not suitable for this library: pytest-dev, tox-dev, click-contribs, pycqa,...

**Comment by JWCook** [comment]
I see. The purpose of Code Shelter is actually fairly similar to jazzband, but not specific to Django or python. It spans both GitHub and GitLab, and doesn't require a repo transfer. So I'd say the scenario of "maintainer disappears, someone else is willing to step up and needs access" is already pretty much covered. That's how I became the current maintainer. That being said, I'm certainly open to working with others interested in keeping this project going long-term. @skorokithakis Feel free to chime in if you have other thoughts on this.

Our current interest in transferring to an org is mainly just so that I (and other future maintainers) could have Owner permissions, in addition to the Collaborator level permissions that Code Shelter provides.

**Comment by skorokithakis** [comment]
No, that's basically spot on, I agree with mostly everything you said, @JWCook.

**Comment by JWCook** [comment]
A beta release is now available on PyPI (`1.0.0b0`). It's possible that a couple more backend-specific changes may still be added, but otherwise I think it's fairly feature-complete at this point.

Testing and feedback would be appreciated!

**Comment by glensc** [comment]
How do you install the beta with pip, pipenv? doesn't get installed with default commands.

**Comment by JWCook** [comment]
Some small updates:
* Another beta release is out (`1.0.0b1`) that includes several bugfixes
* I would still like to get some more feedback on the [new features and other changes](https://github.com/requests-cache/requests-cache/blob/main/HISTORY.md) before releasing
* If nothing else major comes up, I would like to get this released around the **end of February**

**Comment by JWCook** [comment]
Almost everything is ready for release, except for one issue affecting concurrency with the SQLite backend: #781 

If anyone would like to help out, another pair of eyes on that would be appreciated.

**Comment by JWCook** [comment]
I believe this has been fixed, but I'm looking into it a bit more to be sure.

**Comment by JWCook** [comment]
Done! 🚀
