### ISSUE TITLE
Feature request: store contents separately by hash

### ISSUE THREAD

**Issue by dholth** [requests-cache/requests-cache#566]
### Feature description

Store response body separately by a hash of its contents. Continue to store headers and other request metadata in database.

### Use case

Contents can be accessed separately. Identical contents are stored once.

(A more scalable implementation would split into sub-folders based on part of the hash)

https://github.com/dholth/repodata-fly/blob/main/app/contentstore.py

**Comment by JWCook** [comment]
Interesting idea. I'll need a little more detail on what this is meant to accomplish, though.

Is the purpose of this mainly for saving storage space, in a situation where you're expecting a lot of different requests that return the exact same content? If so, a [custom request matcher](https://requests-cache.readthedocs.io/en/stable/user_guide/matching.html#custom-request-matching) might be something to consider.

Or is this mainly so you can access response content outside of requests-cache?
If so, the [filesystem backend](https://requests-cache.readthedocs.io/en/stable/modules/requests_cache.backends.filesystem.html), possibly with a [custom serializer](https://requests-cache.readthedocs.io/en/stable/user_guide/serializers.html#custom-serializers) (if you want compression), is an option.

**Comment by dholth** [comment]
I want the file content without the headers, compressed to save space. Instead of having separate copies of the data in a downloads folder and the cache, I create a link from the download folder into the requests-cache storage. It could be a symlink, a hard link or a copy-on-write reflink. I like having the metadata in sqlite but I'm not using it for anything right now.

In my case the compressed data is about 1/8th as large. With some compression formats like lz4 or zstd it's easy for the compression + (less i/o) to save time overall; don't know if this is the case with gzip -1.

Really I'm just using requests-cache as a way to keep track of caching headers. I could use a convenient way to cache with no storage, and either return "up to date" with no response contents, or "not up to date" with the new contents.

**Comment by JWCook** [comment]
Okay, that makes sense. Roughly how large are these responses? Tens of MB? Hundreds? This is related to #407. Features that I think are good candidates for adding to requests-cache are:
* A backend subclass or option to save response content separately from response/request metadata
* A `CachedSession` method or option to return a response without reading/deserializing its content if not expired
  * Ideally this would also handle 304 responses from conditional requests

**Comment by JWCook** [comment]
Perfect. Do you think this issue can be closed, then?
