### ISSUE TITLE
AttributeError: 'CachedRequest' object has no attribute 'path_url'

### ISSUE THREAD

**Issue by flazzarini** [requests-cache/requests-cache#636]
### The problem
When trying to access ``path_url`` on a given response's initial request.

### Expected behavior
Should behave the same way as the requests library does.

### Steps to reproduce the behavior
```
from requests_cache import CachedSession
from requests import Session


class MySession(Session):
    """
    Custom requests Session
    """

class MyCachedSession(CachedSession):
    """
    Custom Cached Session
    """

# Using standard Session from requests library
session = MySession()
resp = session.get("https://tools.learningcontainer.com/sample-json.json")
resp = session.get("https://tools.learningcontainer.com/sample-json.json")
print(resp.request.path_url)

# Using Cached Session from requests_cached library
session = MyCachedSession()
resp = session.get("https://tools.learningcontainer.com/sample-json.json")
resp = session.get("https://tools.learningcontainer.com/sample-json.json")
print(resp.request.path_url)
```

### Workarounds
Not that I know of

### Environment
- requests-cache version: `0.7.5`
- Python version: [e.g. `3.6`]
- Platform: [e.g. Ubuntu 18.04]

**Comment by JWCook** [comment]
Sure, I can get that added. Thanks for the bug report.

**Comment by flazzarini** [comment]
Unfortunately in the environment where I want to make use of `requests-cache` we are currently stuck with python 3.6, so a backport to the version of `requests-cache` which still supports python 3.6 would be much appreciated.

**Comment by JWCook** [comment]
That's understandable. Would you consider a small workaround? The logic for getting `path_url` is fairly simple: https://github.com/psf/requests/blob/79f2ec3acc4e24fef6e6ce31ad7b1d4e2f77be31/requests/models.py#L85-L104

Here's a minimal example:
```python
from requests_cache import CachedSession
from urllib.parse import urlsplit

def path_url(url: str) -> str:
    p = urlsplit(url)
    url = p.path or '/'
    url += f'?{p.query}' if p.query else ''
    return url

session = MyCachedSession()

# Original response
resp = session.get("https://tools.learningcontainer.com/sample-json.json")
print(path_url(resp.request.url))

# Cached response
resp = session.get("https://tools.learningcontainer.com/sample-json.json")
print(path_url(resp.request.url))
```

**Comment by flazzarini** [comment]
Hi there,

thanks for proposing this solution. Seems a valid alternative to me.

**Comment by JWCook** [comment]
Good! I'll close this issue, then, but feel free to report any other problems you find in 0.7.5 / python 3.6. I'm willing to release more patches for that, if there's a problem that doesn't have workaround available.
