### ISSUE TITLE
Feature request: Add support for Oracle DB

### ISSUE THREAD

**Issue by ppruchnicki** [requests-cache/requests-cache#656]
### Feature description
Add support for Oracle DB

### Use case
Backend Dependencies are full of many, let say free or semi-free options. There is missing connection for more commercial one like Oracle, it would be a nice feature to use module in more commercial projects.

**Comment by JWCook** [comment]
Could you give some more details about your use case? What specific features of Oracle are you interested in using with requests-cache?

**Comment by ppruchnicki** [comment]
Jordan thanks for such quick reply :) mainly possibility to select Oracle as one of 'Backend Dependencies' I worked on several projects that were using Oracle DB as main DB. Possibility to apply ready to go cache mechanism that can reuse the same DB with just different table or schema would be a nice one, instead of choosing and keeping different one only for caching purpose.

**Comment by JWCook** [comment]
Rc oracle

Okay, that makes sense. I think the best way to do this would be a generic relational database backend that takes a SQLAlchemy connection, which would add support for several database types including Oracle.

You would have the option of using either SQLAlchemy 1.4 + `cx_Oracle`, or SQLAlchemy 2.0 pre-release + the newer `python-oracledb` library ([example](https://levelup.gitconnected.com/using-python-oracledb-1-0-with-sqlalchemy-pandas-django-and-flask-5d84e910cb19)).

I would be willing to add this, although it may be awhile until I have time for it. Meanwhile, you could make your own [custom backend](https://requests-cache.readthedocs.io/en/stable/user_guide/backends.html#custom-backends) if you want.

Also, it might be worth trying the default SQLite backend as a temporary solution, if you haven't already. It doesn't require any extra infrastructure, and is generally good enough for medium-sized enterprise applications unless:
1. You have a distributed application with no shared filesystem, or
2. You're making thousands of requests per second on average

**Comment by ppruchnicki** [comment]
Jordan thanks for such quick reply :) mainly possibility to select Oracle as one of 'Backend Dependencies' I worked on several projects that were using Oracle DB as main DB. Possibility to apply ready to go cache mechanism that can reuse the same DB with just different table or schema would be a nice one, instead of choosing and keeping different one only for caching purpose.

**Comment by JWCook** [comment]
@ppruchnicki FYI, I reopened issue #43 for adding a backend for SQLAlchemy-compatible databases.
