### ISSUE TITLE
Can Only URLs Be Stored Without Cached Response Contents?

### ISSUE THREAD

**Issue by kexin9752** [requests-cache/requests-cache#657]
I have stored the response content in my database. I do not want to record the response in the cache database.

**Comment by JWCook** [comment]
One way to do this would be with a [custom serializer](https://requests-cache.readthedocs.io/en/stable/user_guide/serializers.html#custom-serializers). But to convert back into a `requests.Response`-compatible object, you'll need to save all response metadata (except content), not just URLs.

Here is an example that I think will do what you want:
```python
import pickle

from requests_cache import CachedResponse, CachedSession
from requests_cache.serializers import CattrStage, SerializerPipeline


class RemoveContent:
"""Serializer stage that removes response content (stored in a separate database)"""

    def dumps(self, value: CachedResponse) -> CachedResponse:
		     value._content = b''
		     return value
	
    # Any changes when returning a response from the cache would go here
    def loads(self, value: CachedResponse) -> CachedResponse:
    return value


no_content_serializer = SerializerPipeline(
    [RemoveContent(), CattrStage(), pickle],
    name='no_content_pickle',
    is_binary=True,
)
```

Usage example:
```python
session = CachedSession(serializer=no_content_serializer)
r = session.get('https://httpbin.org/get')
r = session.get('https://httpbin.org/get')
print(r.content)
# b''
```

Or you could make a [custom backend](https://requests-cache.readthedocs.io/en/stable/user_guide/backends.html#custom-backends) (or subclass an existing one) if you want more direct control over how responses are saved. Your changes would go in the `__getitem__()` method.

Does that answer your question?

**Comment by JWCook** [comment]
Let me know if you have any more questions, and I can reopen this.
