### ISSUE TITLE
Doesn't work in github Workflows/Actions

### ISSUE THREAD

**Issue by Arthavruksha** [requests-cache/requests-cache#662]
Hi Everyone

I used the Requests_Cache in my local machine and it was caching all requests in a .sqlite file . 

Although when i run the same code in github Workflows/Actions it doesn't cache nor makes a .sqlite file

What's reason for this ??

**Comment by Arthavruksha** [comment]
Any updates over this ?

**Comment by JWCook** [comment]
Without a reproducible example, traceback, or any other details, there is no way to tell what the issue is. Please use the [bug report template](https://github.com/requests-cache/requests-cache/issues/new?assignees=&labels=bug&template=bug.md).

**Comment by Arthavruksha** [comment]
Did it

**Comment by Arthavruksha** [comment]
https://github.com/requests-cache/requests-cache/issues/663
