### ISSUE TITLE
Cache being used for incorrect URL when a query string parameter is duplicated

### ISSUE THREAD

**Issue by gismaps** [requests-cache/requests-cache#677]
### The problem

I have a URL with the same key value ("in") repeated twice in the query string, e.g.: 
https://api.census.gov/data/2020/acs/acs5?get=NAME,B01001_003E&for=block%20group:*&in=county:001&in=state:15

I request the above URL, and then change the first "in" query string value to "county:003". It is a new URL, so I expect it to be sent to the server, but requests_cache is returning the cached result from my first URL. 

### Expected behavior
_A description of what you expected to happen_

I expect each new URL will be sent to the server, not served from cache. 

### Steps to reproduce the behavior

```
import requests_cache
requests_cache.install_cache('census_test', backend='sqlite')
print(f'requests_cache version: {requests_cache.__version__}')

import requests
from urllib.parse import urlparse, parse_qs

url_template = ('https://api.census.gov/data/2020/acs/acs5?'
                'get=NAME,B01001_003E&for=block%20group:*'
                '&in=county:{0}&in=state:15')
fips_codes = {'001': 'Hawaii County', 
              '003': 'Honolulu County', 
              '009': 'Maui County'}

def __fetch_county(url) -> str:
    parsed_url = urlparse(url)
    parsed_qs = parse_qs(parsed_url.query)
    in_keys = parsed_qs['in']
    county = [x for x in in_keys if 'county' in x][0].split(':')[1]
    return county
    
for fips_code, county_name in fips_codes.items():
    url = url_template.format(fips_code)
    r = requests.get(url)    
    print(f'looking for {fips_code} {county_name}')
    print(f'  - URL input matches request URL?: {url == r.url}')
    print(f'    -    input url: {url}')
    print(f'    - response url: {r.url}')
    response_county = __fetch_county(r.url)
    print(f'  - counties match?: {fips_code == response_county}')
    print(f'  - county name in response?: {county_name in r.text}')
```

I expect all the tests above to return True. The first iteration returns True values, but all subsequent iterations are False. Here is the output from the code: 

**NOTE:** My code's output got converted to markdown. It actually looks ok, but isn't what I intended.

requests_cache version: 0.9.5
looking for 001 Hawaii County
  - URL input matches request URL?: True
    -    input url: https://api.census.gov/data/2020/acs/acs5?get=NAME,B01001_003E&for=block%20group:*&in=county:001&in=state:15
    - response url: https://api.census.gov/data/2020/acs/acs5?get=NAME,B01001_003E&for=block%20group:*&in=county:001&in=state:15
  - counties match?: True
  - county name in response?: True
  
looking for 003 Honolulu County
  - URL input matches request URL?: False
    -    input url: https://api.census.gov/data/2020/acs/acs5?get=NAME,B01001_003E&for=block%20group:*&in=county:003&in=state:15
    - response url: https://api.census.gov/data/2020/acs/acs5?get=NAME,B01001_003E&for=block%20group:*&in=county:001&in=state:15
  - counties match?: False
  - county name in response?: False

looking for 009 Maui County
  - URL input matches request URL?: False
    -    input url: https://api.census.gov/data/2020/acs/acs5?get=NAME,B01001_003E&for=block%20group:*&in=county:009&in=state:15
    - response url: https://api.census.gov/data/2020/acs/acs5?get=NAME,B01001_003E&for=block%20group:*&in=county:001&in=state:15
  - counties match?: False
  - county name in response?: False

Note how the response url property does not match the input. The content returned from requests.get() is incorrect, since it is the cached response from the first request. 

### Workarounds

I had an old Conda workspace with requests_cache version 0.5.2 that works fine. Here is the output of the same code above: 

requests_cache version: 0.5.2
looking for 001 Hawaii County
  - URL input matches request URL?: True
    -    input url: https://api.census.gov/data/2020/acs/acs5?get=NAME,B01001_003E&for=block%20group:*&in=county:001&in=state:15
    - response url: https://api.census.gov/data/2020/acs/acs5?get=NAME,B01001_003E&for=block%20group:*&in=county:001&in=state:15
  - counties match?: True
  - county name in response?: True

looking for 003 Honolulu County
  - URL input matches request URL?: True
    -    input url: https://api.census.gov/data/2020/acs/acs5?get=NAME,B01001_003E&for=block%20group:*&in=county:003&in=state:15
    - response url: https://api.census.gov/data/2020/acs/acs5?get=NAME,B01001_003E&for=block%20group:*&in=county:003&in=state:15
  - counties match?: True
  - county name in response?: True

looking for 009 Maui County
  - URL input matches request URL?: True
    -    input url: https://api.census.gov/data/2020/acs/acs5?get=NAME,B01001_003E&for=block%20group:*&in=county:009&in=state:15
    - response url: https://api.census.gov/data/2020/acs/acs5?get=NAME,B01001_003E&for=block%20group:*&in=county:009&in=state:15
  - counties match?: True
  - county name in response?: True

Also, just turning off the caching and using requests.get() without caching works fine. 

### Environment
- requests-cache version: As described above. Was able to reproduce bug on version 0.9.2 and 0.9.5. 
- Python version: 3.7.11
- Platform: Windows 10

**Comment by gismaps** [comment]
Note that my code output samples got converted into a bulleted list via markdown. It looks ok as displayed above, but of course was intended to just be plain text. I added some carriage returns to make it more readable.

**Comment by JWCook** [comment]
Thank you for the details. I should have time to look into this sometime this week.

**Comment by JWCook** [comment]
Fixes for this are in `main`. Can you give that a try and let me know if it's now working as expected for you?

**Comment by gismaps** [comment]
@JWCook - Thanks! Sorry if this is a stupid question, but is there a wheel file available for that? Or do I pull it from PyPI?

**Comment by JWCook** [comment]
There's not a wheel available with these changes yet, but I will probably push out another 1.0 alpha build within the next couple weeks.

Meanwhile, to test out the main branch, you can either `pip install` from github:
```
pip install git+https://github.com/requests-cache/requests-cache
```

Or follow the setup steps for local development here: https://github.com/requests-cache/requests-cache/blob/main/CONTRIBUTING.md#dev-installation.

**Comment by JWCook** [comment]
I'm going to go ahead and mark this as closed since it seems to be working based on my tests, but please feel free to open another issue if you run into any more problems. Thanks!
