### ISSUE TITLE
Will cache key resolution remain the same from 0.9 to 1.0?

### ISSUE THREAD

**Issue by bvacherot-sofar** [requests-cache/requests-cache#678]
Hello,

I noticed different cache key resolution for the same URL_s between from version 0.9.3 to 1.0.0a1. This meant that caches generated from the 0.9.3 version were incompatible with the 1.0.0a1 logic as the key_s did not line up.

Only change on my end was the package version (I wanted to use the `only_if_cached` feature - which btw worked great for me).

Wondering if this is a known and expected behavior of the newer package version. If not, will gladly open up a fuller fledged bug report. 

Thank you!

**Comment by JWCook** [comment]
> Wondering if this is a known and expected behavior of the newer package version.

Yes, unfortunately the cache keys change for almost every non-patch release. New features and other changes related to request matching have been fairly frequent, and each of those results in different cache keys.

In most use cases cache data is short-lived, so it's usually not a problem, but I understand if you use a long expiration plus `only_if_cached`, you may want to keep your data after a library update. Currently that's possible, but it's a bit clunky. I could make some changes to make that easier, maybe with a new method like `CachedSession.cache.recreate_keys()`.

**Comment by bvacherot-sofar** [comment]
Thank you for the clarity on this. It makes sense that these new features would change the cache keys. 

We currently use `request-cache` for a task "replay" feature. We cache responses for a worker task, and store them. We can then replay the worker by downloading the cache and replaying the worker and its decisions. The cached responses allow us to ensure that the worker always runs with the same responses. This is useful for local debugging of failing workers.

So we will have to be aware of this when updating package version. I'd love to learn more about the mechanisms to update the cache keys if they exist. Could you point me to some of the functions that do so? Thank you!

**Comment by JWCook** [comment]
Some changes are now in `main` to make this easier. Now you can run this after updating to a new requests-cache version, or after changing any settings related to [request matching](https://requests-cache.readthedocs.io/en/stable/user_guide/matching.html):
```python
session.cache.recreate_keys()
```

Give that a try, and let me know if that does what you want.

**Comment by JWCook** [comment]
I'll close this issue for now, but let me know if you have any more questions or problems. Thanks!

**Comment by bvacherot-sofar** [comment]
Thank you for looking into this. Apologies, I let this fall through. I scheduled some time this week to answer your question.

**Comment by bvacherot-sofar** [comment]
Hi, just tried this and did not quite get the expected behavior. Cache keys were different when the keys were recreated.

The `request.body` for the cached version was `b'None'`, whereas it was `None` for the new version. Forcing `request.body` to be `None` in the key creation function in these cases made `recreate_keys()` work perfectly.  

`cache_keys.py:create_key()`

Not sure where this difference comes from, but thought you might be curious or have some insight on it. 

In any case, thank you so much so building this feature!

**Comment by JWCook** [comment]
Previously, an empty request body would get stringified into `b'None'`, which wasn't intentional. I believe I changed that in 0.9.0.

Sounds like you already found a workaround. One area for improvement, though, would be in the automated tests. I've already been adding sample cache files created with every requests-cache version and just testing to make sure that after updating, old cache contents are either reused or replaced without any errors.

If you wanted to add any more tests for update-related issues relevant to your use case, that would be a good place to do it.
