### ISSUE TITLE
Question or Feature Request

### ISSUE THREAD

**Issue by mzpqnxow** [requests-cache/requests-cache#683]
Hello, thanks for the your work on this project

I wanted to get your take on something and possibly ask for or offer a feature as a PR

In several applications I use my own extensions of `requests.Session`, or a third-party extension of `requests.Session`

The simplest example for the purpose of demonstrating what I'm interested in is `BaseUrlSession` (provided by [requests-toolbelt](https://github.com/requests/toolbelt))

If you're not familiar with that one, it's pretty contrived (though useful) it just associates a base URL with the session, so you don't need to specify the full URL each time you make a request. It's so simple it's easiest to just point you at the implementation:

https://github.com/requests/toolbelt/blob/master/requests_toolbelt/sessions.py

What I would like to be able to do is provide either the `BaseUrlSession` class (effectively as a "factory") to `requests-cache` *or* pass an already instantiated `BaseUrlSession` to `requests-cache`

## Current requests-cache pattern

```python
session = requests_cache.CachedSession('demo_cache')
```

## Desired supported patterns

First, using an arbitrary session "factory" class. It's assumed that the class would have to not do certain things that might interfere with the internals of `requests-cache`:

```python
class MySession(requests.Session):
    ...

caching_session = requests_cache.CachedSessionFromFactory(..., factory=MySession)
```

Alternately/additionally, "applying" caching to an already instantiated `requests.Session` or descendant of `requests.Session`:

```python
session = requests.Session()
caching_session = requests_cache.apply_caching(session)
```

These are both admittedly pretty contrived examples. I can give you a better example for the second one (or a use-case, at least)

Consider a third-party Python package a vendor publishes to interact with their product. In that implementation, there is ultimately a `requests.Session` underneath. Something like:

```python
from vendorco import VendorAPI
v = VendorAPI(credentials=...)
requests_cache.apply_caching(v._session)
v.call_some_endpoint()
```

Hope this makes sense and doesn't seem like an extremely niche case :)

## Workarounds / Alternatives

- Forking, hard-coding the change (`requests-baseurlsession-cache`)
- Copying `requests-cache` into my project trees as needed, with the changes
- Applying the caching globally, via `requests_cache.install_cache('demo_cache')` (works fine unless there are other sessions/requests that you want exempted from the caching)

## Notes, etc.

From what I can tell, given the current design of `requests-cache` (as a mix-in that effectively extends `requests.Session`) there's no "clean" way to do this aside from modifying `MIXIN_BASE` (which is `requests.Session`). This approach would work but it's not something that can be done cleanly/dynamically

I admit that I haven't yet looked deeply into `CacheMixin`, but I'm wondering if you have any thoughts on the _best_ way to do this. Ideally I would like to be able to submit a PR if you're interested in supporting this pattern. If not, I'd still value your opinion or advice on how to approach it, even if it ends up being a minor fork, or a local modification that I include in my source trees

Ideally, any solution would allow passing through args/kwargs to the session factory that's provided, but that's not necessary and may not be worth the trouble. The "hack" I use for this now whenever I need to use `BaseUrlSession` as a factory to other interfaces uses `partial`, e.g.

```
from requests_toolbelt.sessions import BaseUrlSession
from functools import partial
BASE_URL = "https://some.site.com/api/v1/"
session_factory = partial(BaseUrlSession, BASE_URL)

third_party_package_doing_requests_stuff(arg1, arg2, ..., session_factory=session_factory)
```

I ran into the `Session` factory pattern when using some third-party multithreading abstractions and when designing my own class that used the composition approach for customizing a `Session`, rather than the mixin/inheritance approach

_**tl; dr; any interest in supporting caching for already-instantiated classes or for specifying an arbitrary extension of `requests.Session` as a factory, to override the default?**_

## Caveats

- I realize this may require invasive changes due to potential design conflict, which is why I'm expecting you to not be too interested in explicitly supporting this
- Similarly, I wouldn't expect this to necessarily be a "core" / supported feature of `requests-cache` _if_ you were interested in implementing it or accepting a PR. It would probably make most sense in an `experimental`/`extras`/`contrib` package within the `requests-cache` package. I say this because not all extensions of `requests.Session` that I've seen are very thoughtfully implemented and may very well clash with/break things that the `requests-cache` extension is doing

Thanks again!

**Comment by mzpqnxow** [comment]
I see now there is a `session_factory` kwarg in `install_cache` ... though it's not quite what I'm describing, it may fall into the category of alternate approaches. Ditto with `filter_fn`

I can take a deeper look into solutions with these first

**Comment by mzpqnxow** [comment]
OK, after looking through the source and examples, I see a lot of workarounds that are far superior to introducing new code into the project. Sorry for the distraction!

**Comment by JWCook** [comment]
Not at all, these are good questions. Playing nicely with other `requests`-based libraries is intended to be a feature of requests-cache. Check out this section of the docs, I think it will answer most of your questions: https://requests-cache.readthedocs.io/en/stable/user_guide/compatibility.html

You should be able to do what you want with `CacheMixin`, which has no base class (just `object`) and is meant for cooperative inheritance. That `MIXIN_BASE` thing you see is only for type checking.

**Comment by mzpqnxow** [comment]
BTW, it worked just as all of the other examples worked, probably no surprise to you ;)

The following was sufficient:


```
class CachedBaseUrlSession(CacheMixin, BaseUrlSession):
    """Extend with BaseUrlSession to facilitate lazyness"""
```
