### ISSUE TITLE
Feature request: Django Cache backend

### ISSUE THREAD

**Issue by gone** [requests-cache/requests-cache#685]
### Feature description
I would love to way to reuse my django app's existing cache as a cache backend

### Use case
Reduce configuration and centralize caching

### Workarounds
not really

### Plan to implement
If there's interest I'd be happy to take a shot

**Comment by JWCook** [comment]
Could you explain a bit more what you would like to do?

Django's cache system supports a few different backends. Which one are you using? For example, both Django and requests-cache support Redis, so you could use the same Redis instance for both, if you wanted. Is that what you mean?

**Comment by gone** [comment]
Yeah - that's what I'm thinking. Some way where I can say "whatever django is using for the cache, just use that" vs having two different configuration blocks one for django and one for requests. 

I'm thinking implementation wise it would use the django.cache get/set facade as the interface to the cache vs the underlying redis/sqllite library.

**Comment by JWCook** [comment]
Got it. I think this would make more sense as a library feature if both requests-cache and Django supported the same backends, but I believe Redis is the only one they have in common. Maybe the filesystem backend too, if you want to count that. requests-cache doesn't support Memcached (although [it would be possible](https://github.com/requests-cache/requests-cache/issues/348)), and as far as I know Django doesn't support SQLite (except via other libraries like [diskcache](https://github.com/grantjenks/python-diskcache)), MongoDB, or DynamoDB. Also, this library is really focused on client-side requests, not server-side, so I don't think I would want to directly maintain any Django-specific features here.

However, this is probably something that would be useful to others, so you could potentially make a separate repo for this, which I could then link to in the requests-cache docs. Or, if it would fit in a single module, that might be a good addition to the [examples](https://github.com/requests-cache/requests-cache/tree/main/examples) folder, if you would like to submit a PR for that.

What do you think?

**Comment by gone** [comment]
I'd be happy to do it in a extension vs the core project.

**Comment by JWCook** [comment]
Let me know if/when you make something like that, and I can link to it from the requests-cache docs.
