### ISSUE TITLE
Cache does not recover if physical sqlite file has been removed. 

### ISSUE THREAD

**Issue by srinath-ragh** [requests-cache/requests-cache#69]
The next time requests gets called, it comes back with "no such table: responses" and never recovers after that. Using requests-cache==0.4.12. Not sure if I am doing something wrong?

Thanks!

**Comment by reclosedev** [comment]
Can you provide steps to reproduce?

If sqlite file is deleted library creates it again.

**Comment by srinath-ragh** [comment]
@reclosedev 

Python 3.4.4 (default, Dec 22 2015, 17:39:35) 
[GCC 4.6.3] on linux
Type "help", "copyright", "credits" or "license" for more information.

import requests
import requests_cache
requests_cache.install_cache(cache_name='test_cache', backend='sqlite', expire_after=300)
def rest(url):
    try:
            response=requests.get(url).json()
            print(response)
            return (response)
    except Exception as e:
            print(e)
            return ""

... 
>>> rest("http://jsonplaceholder.typicode.com/posts/1")
{'userId': 1, 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto', 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit'}
{'userId': 1, 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto', 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit'}
>>> rest("http://jsonplaceholder.typicode.com/posts/1")
{'userId': 1, 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto', 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit'}
{'userId': 1, 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto', 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit'}

**At this point delete the sqlite cache**

>>> rest("http://jsonplaceholder.typicode.com/posts/1")
**no such table: responses
''**
>>>

**Comment by JWCook** [comment]
The issue here is that sqlite will recreate the database file if it's deleted, but will only create the table when the cache is first initialized.

@srinath-ragh It would be possible to check if the table exists on every cache read or write (or handle it in a try-except block), if that's something you need. Is this something you'd like to submit a PR for?

**Comment by JWCook** [comment]
Since this is a pretty old issue, I'm going to close this for now, but if this is a feature anyone else needs or wants to make a PR for, please comment and I'll reopen it.
