### ISSUE TITLE
Incompatibility with `OAuth1` by `requests-oauthlib`

### ISSUE THREAD

**Issue by eserdk** [requests-cache/requests-cache#705]
### The problem
When using `requests-cache` together with `OAuth1` auth or `OAuth1Session` from `requests-oauthlib`, `get_cache_directives` fails because `OAuth1` auth casts header values to bytes (particularly, `Cache-Control`) during `prepare_request`, while `get_cache_directives` expects headers to be strings. 

This causes the following error:
```python
Exception has occurred: TypeError a bytes-like object is required, not 'str'
  File "[REDACTED]/requests_cache/cache_control.py", line 190, in get_cache_directives
    cache_directives = headers['Cache-Control'].split(',')
  File "[REDACTED]/requests_cache/cache_control.py", line 85, in from_request
    directives = get_cache_directives(request.headers)
  File "[REDACTED]/requests_cache/session.py", line 128, in send
    actions = CacheActions.from_request(
  File "[REDACTED]/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "[REDACTED]/requests_cache/session.py", line 115, in request
    return super().request(method, url, *args, **kwargs)
```

**Note**, this might also be a problem in `main` branch, though I haven't checked it by myself: https://github.com/requests-cache/requests-cache/blob/main/requests_cache/policy/directives.py#L36.

### Expected behavior
Headers are parsed and handled properly, without raising an error even if they are bytes.

### Steps to reproduce the behavior
1. Create a `CachedSession` instance
2. Make a request to somewhere, having `auth` parameter set to a `requests_oauthlib.OAuth1` instance and `expire_after` to a non-negative number (`Cache-Control` header needs to be not `None`)
3. See the error here: https://github.com/requests-cache/requests-cache/blob/170a627e086baca8d4d3fd4c6cfa960123311b5b/requests_cache/cache_control.py#L190

### Workarounds
I'd say it **might** be possible to solve this by converting headers (or just the specific ones) back to strings before handling them.

### Environment
- requests-cache version: `0.9.6`
- Python version: `3.9.10`
- Platform: any
- requests-oauthlib version: `1.3.1`

**Comment by JWCook** [comment]
This looks easy enough to fix. Thanks for reporting it!

**Comment by JWCook** [comment]
This is fixed in main, and will be included in a patch release within the next couple weeks.

**Comment by JWCook** [comment]
This is now fixed in 0.9.7.

**Comment by eserdk** [comment]
@JWCook thanks! I'll try using it soon.

**Comment by eserdk** [comment]
Can confirm it now works perfectly in our case. Thanks for fixing this!
