### ISSUE TITLE
CachedSession are Pickable but are corrupted when extracted.

### ISSUE THREAD

**Issue by rgammans** [requests-cache/requests-cache#707]
### The problem
CachedSession is sliced by pickling.

Any CachedSession loaded from a pickle no longer has `cache` attribute.

### Expected behaviour
either CachedSession should be unpickable (__getstate__() raise on exception) , or it should override requests.Session's __getstate__ and __setstate__ methods.

### Steps to reproduce the behaviour
_With a complete code example, if possible_
Create a cached session sess.
then:

```
>>> session=requests_cache.CachedSession()
>>> session.get("http://google.com")
<Response [200]>
>>> import pickle
>>> s=pickle.dumps(session)
>>> session2=pickle.loads(s)
>>> session2.get("http://google.com")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/roger/.local/share/virtualenvs/epf_consolidation-1RtUKbIj/lib/python3.8/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/roger/.local/share/virtualenvs/epf_consolidation-1RtUKbIj/lib/python3.8/site-packages/requests_cache/session.py", line 115, in request
    return super().request(method, url, *args, **kwargs)
  File "/home/roger/.local/share/virtualenvs/epf_consolidation-1RtUKbIj/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/roger/.local/share/virtualenvs/epf_consolidation-1RtUKbIj/lib/python3.8/site-packages/requests_cache/session.py", line 127, in send
    cache_key = self.cache.create_key(request, **kwargs)
AttributeError: 'CachedSession' object has no attribute 'cache'
```

### Workarounds
None. Don't pickle CachedSessions, but an error when you try to pickle would be better than falling oddly like this.

### Environment
- requests-cache version: (for example, `0.9.6` or `main`)
- Python version: (for example, `3.8`)
- Platform: (for example, Debian 10 & 11)

**Comment by JWCook** [comment]
Good to know, thanks for reporting this. Raising an exception is probably the best thing to do here, since I don't think we would be able to consistently support pickling that `CachedSession.cache` object for all backend types. I'll get that added in the next patch release.

**Comment by JWCook** [comment]
Well, I guess adding support for pickling `CachedSession` could potentially be done by allowing `cache` to be omitted by `__setstate__()` and then re-initialized it on demand. But that might require some breaking changes, so I would rather avoid that unless there's a good reason for it.

Just curious, did you run into this when using requests-cache with multiprocessing, or something else?

**Comment by rgammans** [comment]
`cache` and other attributes is already omitted by the requests.Session's `__getstate__()`. 
But Recreating a backend on `__setstate__()` rather than trying to pickle it would be the way I'd implement picklability for these objects.

And yes I was using multiprocessing, I have a data processing task which reads a lot of data from a REST source, I put the individual processing jobs into a `multiprocessing.Queue`.  

One of the task description objects contain(s/ed) a session object. In the end I switched the using a global session initialised before fork() .

**Comment by JWCook** [comment]
This is fixed in main, and will be included in a patch release within the next couple weeks. You will now get a `NotImplementedError` when attempting to pickle `CachedSession`, instead of an `AttributeError` when unpickling.

**Comment by JWCook** [comment]
> Recreating a backend on `__setstate__()` rather than trying to pickle it would be the way I'd implement picklability for these objects.

Good point, that does make sense. Most of the backends would be rather difficult to re-initialize reliably, though. For example, the Redis, MongoDB, and DynamoDB backends allow you to pass a connection object, like:
```python
from redis import Redis
from requests_cache import CachedSession, RedisCache

connection = Redis(host='...', port=6379, password='...', ssl_keyfile='...', socket_timeout=5)
session = CachedSession(backend=RedisCache(connection=connection))
```

For requests-cache to recreate that `connection` object, since it doesn't have access to its original init kwargs, it would have to look for the connection settings saved in `Redis.connection_pool.connection_kwargs`, and then filter/translate those back into init kwargs for `redis.Redis`. That seems fairly messy, and likely to break with future redis-py updates. So I think it would only make sense to support pickling the Redis backend if redis-py itself supported pickling.

For the default SQLite backend, it would be a little more manageable, but even that would get messy because there could be additional state information added or modified after initialization (like `PRAGMA` settings).

Trying to pickle connection objects seems like a bad idea, and for python and multiprocessing in general, best practice is always to create a new connection for each process.

**Comment by rgammans** [comment]
> Trying to pickle connection objects seems like a bad idea, and for python and multiprocessing in general, best practice is always to create a new connection for each process.

Agreed, If you can't recreate a backend with new connection objects, as opposed to pickled and reanimated, then it's not sensible to implement picklablity

**Comment by JWCook** [comment]
This is now fixed in 0.9.7.

**Comment by Shaked** [comment]
@JWCook what would be the right way to add a `CustomCachedSessionWithPickleSupport`? I would like to use it with a Redis backend.

**Comment by JWCook** [comment]
@Shaked I believe the best way to do that would be:
* Store a copy of your backend initialization arguments, if any (`host`, `port`, etc.) on the session object
* Skip `self.cache` in `__getstate__()`
* Re-initialize `self.cache` in `__setstate__()`
* There are some more details on those methods here: https://docs.python.org/3/library/pickle.html#object.__getstate__

**Comment by Shaked** [comment]
@JWCook 

I have tried playing with the idea that you have mentioned, using:

```
class CustomCachedSessionWithPickleSupport(CachedSession):
    def __getstate__(self):
      self.cache = None
      return self.__dict__ 

    def __setstate__(self, state):
        self.cache = init_backend(config['cache_name'], config['cache_options'], config['cache_backend'])

    install_cache(
        backend=RedisCache(host=app.config["REDIS_HOST"], port=app.config["REDIS_PORT"], db=app.config["REDIS_DB"]),
        session_factory=CustomCachedSessionWithPickleSupport,
        # backend="filesystem",
        cache_control=True,
        serializer="pickle",
        urls_expire_after={
            '*.github.com': 86400,  # Placeholder expiration - one day; should be overridden by Cache-Control
            '*': DO_NOT_CACHE,  # Don't cache anything other than GitHub requests
        }
    )
```

I also played with several variations of `CustomCachedSessionWithPickleSupport` but I keep seeing the following error: 

> Can't pickle local object 'install_cache.<locals>._ConfiguredCachedSession'

Any chance you could give me a hint how to make this work?

**Comment by JWCook** [comment]
You're almost there! It looks like you're saving to two separate caches. When you initialize the session for the first time, you're not giving it any backend settings, so it will use the default (SQLite). When you unpickle the session, a new cache will be created using Redis.
```python
print(session.cache)
print(session2.cache)
```

You won't be able to use `install_cache` with a session object that you pickle and unpickle, unless you add some very hacky and error-prone workarounds. `install_cache` patches the `requests.Session` class, not an object. It's also not thread-safe or multiprocess safe, in case you're trying to pickle the session to pass to multiple processes. And if you are doing that, it would be better to create a new session object for each process.

There are more details on how `requests.Session` works in general here: https://requests.readthedocs.io/en/latest/user/advanced/
And there's a summary of using `CachedSession` vs `install_cache()` here: https://requests-cache.readthedocs.io/en/stable/user_guide/general.html

**Comment by Shaked** [comment]
@JWCook Thank you for this. I managed to make it work in case anyone is interested: 

```python
from logging import getLogger
from multiprocessing import RLock

import loguru
import requests
from flask import current_app
from requests_cache import CachedSession, RedisCache, init_backend


class CustomCachedSessionWithPickleSupport(CachedSession):
    app = None

    def __init__(self, *args, **kwargs):
        with CustomCachedSessionWithPickleSupport.app.app_context():
            config = CustomCachedSessionWithPickleSupport.app.config
            backend = RedisCache(
                host=config["REDIS_HOST"],
                port=config["REDIS_PORT"],
                db=config["REDIS_DB"]
            )
            self.backend = backend
            kwargs['backend'] = backend
            super().__init__(*args, **kwargs)

    def __getstate__(self):
        loguru.logger.debug('PICKLING')
        self.cache = None
        self.filter_fn = None
        self._lock = None
        self.backend = None
        return self.__dict__

    def __setstate__(self, state):
        loguru.logger.debug('UNPICKLING')
        with CustomCachedSessionWithPickleSupport.app.app_context():
            config = CustomCachedSessionWithPickleSupport.app.config
            backend = RedisCache(
                host=config["REDIS_HOST"],
                port=config["REDIS_PORT"],
                db=config["REDIS_DB"]
            )
            cache = init_backend('http_cache', backend)
            state['cache'] = cache
            state['_lock'] = RLock()
            state['filter_fn'] = lambda r: True
            self.__dict__.update(state)

    @staticmethod
    def register(app):
        loguru.logger.debug('Registering CustomCachedSessionWithPickleSupport: {}', app.config["REQUESTS_CACHE_ENABLED"])
        if app.config["REQUESTS_CACHE_ENABLED"]:
            logger = getLogger('requests_cache')
            logger.setLevel(app.config['REQUESTS_CACHE_LOG_LEVEL'])

            CustomCachedSessionWithPickleSupport.app = app
            requests.Session = requests.sessions.Session = CustomCachedSessionWithPickleSupport
``` 

Some explanation about this: 

- I needed requests-cache to work with Flask, therefore I have the static `register` method with a configuration flag.
- That enables me to use `CustomCachedSessionWithPickleSupport.register(app)` from within the app.py, which exposes the app context and its application config. 
- I needed the config because I wanted to inject my Redis configuration the same way as I inject my config within my Flask app. 
- Using the `backend` in the `__init__` method indeed worked as you have mentioned in the previous comment. 

Thanks again for your time and help - and if you have any suggestions to improve the above code, please let me know
