### ISSUE TITLE
Get count of cached responses

### ISSUE THREAD

**Issue by JWCook** [requests-cache/requests-cache#711]
Continuing from https://github.com/requests-cache/requests-cache/commit/35b48cf3486e546a5e4090e8e410b698e8a6b7be#r87356998

@glensc I'm open to suggestions for how you'd like to get cache stats; the only thing I want to avoid is putting any backend method calls inside `__str__()`.

For just a count of cached responses: here are a few options:
* `len(CachedSession.cache.responses)`: a fast, lower-level call that doesn't do any filtering. In SQLite, for example, this is just doing a `SELECT COUNT` instead of loading and deserializing responses into memory.
* [`CachedSession.cache.filter()`](https://requests-cache.readthedocs.io/en/main/modules/requests_cache.backends.base.html#requests_cache.backends.base.BaseCache.filter): This is being added in 1.0, which wraps `responses` with some extra filtering options. That returns a generator, so you can call `len(list())` on those results.
* [`CachedSession.cache.response_count()`](https://requests-cache.readthedocs.io/en/stable/modules/requests_cache.backends.base.html#requests_cache.backends.base.BaseCache.response_count): This is one I was planning to deprecate in 1.0 and remove in a later release (in favor of using one of the two above options), but I'm fine with keeping it around if you find that more convenient.

**Comment by glensc** [comment]
Thanks, I'll go with `len(CachedSession.cache.responses)`:
- https://github.com/Taxel/PlexTraktSync/pull/1115/files

even maybe simplify and remove `len(redirects)` if that becomes broken, currently, in the specific app, it's (so far) `0` anyway all the time.

**Comment by JWCook** [comment]
Right, unless the sites you're hitting make heavy use of redirects, that usually won't be useful information.

Is there any other information you'd like to get out of the cache besides response count?

**Comment by JWCook** [comment]
@glensc I took a quick look at your `cache.py` from that PR you linked, to check if the next release might give you any other problems.

Here's one possible improvement: Instead of `getattr(session.cache, "values", None)` [here](https://github.com/Taxel/PlexTraktSync/blob/3c38ab4a9694ff243f75ef951facb1d27a223c4b/plextraktsync/commands/cache.py#L10), you can use `session.cache.responses.values`. That works for any requests-cache version all the way back to the first release (0.1.0).

The only thing different in `session.cache.values` is some extra filtering options, which will be combined with a few other features into a separate [`filter()`](https://requests-cache.readthedocs.io/en/main/modules/requests_cache.backends.base.html#requests_cache.backends.base.BaseCache.filter) method.

**Comment by glensc** [comment]
makes sense as the rest of the code already uses that property:
- https://github.com/Taxel/PlexTraktSync/blob/3c38ab4a9694ff243f75ef951facb1d27a223c4b/plextraktsync/commands/cache.py#L56

**Comment by glensc** [comment]
https://github.com/Taxel/PlexTraktSync/pull/1224
