### ISSUE TITLE
Pytest failing due to unexpected keyword argument 'omit_if_default'

### ISSUE THREAD

**Issue by gsalvatella** [requests-cache/requests-cache#719]
### The problem
Pytest fails due to unexpected keyword argument 'omit_if_default'

### Expected behavior
pytest succeeds

### Steps to reproduce the behavior
```bash
$ python -m pytest
ImportError while loading conftest '$HOME/repos/requests-cache/tests/conftest.py'.
tests/conftest.py:30: in <module>
    from requests_cache import ALL_METHODS, CachedSession, install_cache, uninstall_cache
requests_cache/__init__.py:7: in <module>
    from .backends import *
requests_cache/backends/__init__.py:7: in <module>
    from .base import BaseCache, BaseStorage, DictStorage
requests_cache/backends/base.py:22: in <module>
    from ..serializers import SERIALIZERS, SerializerPipeline, SerializerType, pickle_serializer
requests_cache/serializers/__init__.py:26: in <module>
    from .preconf import (
requests_cache/serializers/preconf.py:26: in <module>
    base_stage = CattrStage()  #: Base stage for all serializer pipelines
requests_cache/serializers/cattrs.py:55: in __init__
    self.converter = init_converter(factory, **kwargs)
requests_cache/serializers/cattrs.py:84: in init_converter
    converter = factory(omit_if_default=True)
E   TypeError: Converter.__init__() got an unexpected keyword argument 'omit_if_default'

### Environment
- requests-cache version: 0.9.7
- Python version: 3.10.7
- Platform: manjaro/arch

**Comment by JWCook** [comment]
Can you show me the output of `pip freeze`? An older version of `cattrs` could be the problem.

**Comment by JWCook** [comment]
Confirmed that this occurs with cattrs <=22.1. That's going to be a confusing error for most people, though, so I added handling for this in `main`. I could release a patch for this for 0.9 if needed, but first I'd like to figure out why cattrs didn't get updated. The pinned minimum version is 22.2, and that's in the package metadata, so pip/poetry/etc. should have updated that for you.

@gsalvatella Did you encounter this by checking out the requests-cache repo locally? Or did you install requests-cache from PyPI? If so, what version of pip (or other package manager) do you have?

**Comment by gsalvatella** [comment]
I confirm that my system is using  `cattrs==22.1.0`. 

This problem shows up both in locally checked out repo and during installation of the AUR package `python-requests-cache`.  I see now you have addressed this in https://aur.archlinux.org/packages/python-requests-cache. It seems indeed that the `cattrs` package version is correct in the arch repository, but for some reason it still shows 22.1 with `pacman -Ss python-cattrs`...

**Comment by gsalvatella** [comment]
I think you can close this issue. `python-cattrs` has been updated now.

**Comment by JWCook** [comment]
Good to know, thanks!
