### ISSUE TITLE
Make CachedResponse.cache_key available from all cache access methods

### ISSUE THREAD

**Issue by JWCook** [requests-cache/requests-cache#746]
Follow-up from #745. Currently, `CachedResponse.cache_key` is set in `BaseCache.get_response()`, so it won't be set in cases like:
* `session.cache.responses[cache_key]`
* `session.cache.responses.items()`
* `session.cache.responses.values()`
* And any other path that doesn't go through `BaseCache.get_response()`

I think this could be moved to the `__getitem__` method of every backend storage class.

**Comment by glensc** [comment]
not sure what is `__getitem__` implementation referred here, but you can use `@property` decorator to make property-like access actually a function:

```py
@property
def cache_key(self):
  if self._computed_cache_key is None:
    self._computed_cache_key = cache_key(self)
  return self._computed_cache_key
```

```py
print(response.cache_key)
```

maybe this is helpful.

**Comment by JWCook** [comment]
That's a good idea. The only problem is in cases like the one you encountered, where the response was cached with a different requests-cache version and the new cache key doesn't match the one actually stored in the cache.

`__getitem__` is the lowest-level method for reading from each cache backend ([for example, [the SQLite version here](https://github.com/requests-cache/requests-cache/blob/32830cdef20c9aa6bed4de117aca82ba0d64b1ab/requests_cache/backends/sqlite.py#L255-L262)), and all other read methods ('values()`, `items()`, `get_response()`, etc.) will call that.
