### ISSUE TITLE
Feature request: Keep old responses instead of overwriting

### ISSUE THREAD

**Issue by DarioHett** [requests-cache/requests-cache#752]
### Feature description
Currently a new response just overwrites an expired cached response. For later auditing, it would be nice to have a prior version of a response without duplicating the entire database and manually investigating differences.

### Use case
_Is there a specific goal that this would help you accomplish, or can you provide any other context about how you would like to use this feature?_
A response might change various reasons such as forecast updates; it would be nice to be able to update the cached value without removing existing information.

### Workarounds
_Is there an existing workaround to accomplish this?_
No clean ways as created_at information would have to be incorporated in the key_fn, if we were to use a single backend. One way would be to use multiple backends ordered by recency.

### Plan to implement
_Are you interested in submitting a PR to implement this?_
Potential interest, I haven't worked much with this package yet and would require some pointers.

**Comment by JWCook** [comment]
Keeping a history of cached responses is out of scope for this library, but this could be done with a session subclass. The easiest way to do it would be to store a copy of every response, with created_at appended to the cache key. Here's an example:

```python
from requests_cache import CachedSession


class CachedHistorySession(CachedSession):
    """A CachedSession that keeps a copy of all previously cached responses"""

    def send(self, *args, **kwargs):
        """Save a copy of every new response"""
        response = super().send(*args, **kwargs)
        if not response.from_cache:
            self.cache.save_response(response, f'{response.cache_key}_{response.created_at}')
        return response

    def get_response_history(self, response):
        """Get a history of previously cached versions of the given response"""
        return [
            self.cache.responses[k]
            for k in self.cache.responses.keys()
            if k.startswith(response.cache_key) and k != response.cache_key
        ]
```

Usage example:
```python
from time import sleep

session = CachedHistorySession(expire_after=1)
n_history_items = 3
for i in range(n_history_items):
    response = session.get('https://httpbin.org/get')
    if i < n_history_items - 1:
        sleep(1)

for r in session.get_response_history(response):
    print(r)
```

A potential improvement, if needed: If you had a very large cache and needed `get_response_history()` to be faster, you could subclass the SQLite backend and add an indexed column for the original cache key, which could then be queried with something like
```sql
SELECT value FROM responses WHERE original_key=?
```

Let me know if that answers your question.

**Comment by JWCook** [comment]
I'll close this for now, but let me know if you have any more questions.
