### ISSUE TITLE
CachedSession urls_expire_after caches forever?

### ISSUE THREAD

**Issue by glensc** [requests-cache/requests-cache#762]
### The problem

So, I've created `CachedSession` with `urls_expire_after` to set one pattern to cache "1 day", I make the item into a cache, I change the rule to say "1m" and it's still taken from the cache.

and if I `str(response)` it prints `expires: N/A`:

```html
<!-- request: GET https://example.org, response: 200 (7.57 KiB), created: 2023-01-13 02:12:56 EET, expires: N/A (fresh) -->
```

### Expected behavior

1. `expires: `should print date when the item expires
2. lowering expiration should refresh the item in the cache

### Steps to reproduce the behavior

```py
#!/usr/bin/env python
from requests_cache import CachedSession

url = "https://httpbin.org/anything?4"
urls_expire_after = {
    "*": "1 second",
}
session = CachedSession(
    urls_expire_after=urls_expire_after,
)

print(f"1. GET {url}")
response = session.get(url)
print(response)
print(type(response))

print(f"2. GET {url}")
response = session.get(url)
print(response)
print(type(response))
```

this prints:

```
1. GET https://httpbin.org/anything?4
<Response [200]>
<class 'requests.models.Response'>
2. GET https://httpbin.org/anything?4
request: GET https://httpbin.org/anything?4, response: 200 (412 bytes), created: 2023-01-13 02:36:11 EET, expires: N/A (fresh)
<class 'requests_cache.models.response.CachedResponse'>
```

and if you retry after 1 second the same script, it will take both requests from cache:

```
➜ python test_request_cache_762.py
1. GET https://httpbin.org/anything?4
request: GET https://httpbin.org/anything?4, response: 200 (412 bytes), created: 2023-01-13 02:36:11 EET, expires: N/A (fresh)
<class 'requests_cache.models.response.CachedResponse'>
2. GET https://httpbin.org/anything?4
request: GET https://httpbin.org/anything?4, response: 200 (412 bytes), created: 2023-01-13 02:36:11 EET, expires: N/A (fresh)
<class 'requests_cache.models.response.CachedResponse'>
```

### Workarounds

Ignore the problem, and delete the cache when needed.

### Environment
- requests-cache version: 0.9.7

**Comment by glensc** [comment]
Ok, here's what I found out meanwhile:
1. anything it doesn't recognize is logged with debug as failed to parse http date and treated as "forever" (in fact I never saw those errors in my application, but maybe items were already cached, see 3. point below)
1. `str("1")` is not treated as `int(1)`, falls into the "unknown" category (unexpected bug)
2. so things like "1d", "3w" are unknown and cached forever
3. adding new expiry via rules is ignored, it respects only expiry from cache (unexpected feature/bug!)

the `str("1")` vs `int(1)` does not affect my codebase as I load data from yaml and yaml convers all number-like values to `int`, but it was visible in this reproducer.

I'm really expecting some simple unit processing to be supported, like "1d", "3w", "9y", this should be trivial to implement,  currently I'm looking at using [strtotime](https://pypi.org/project/strtotime/) in my project, it's large library and I want just simple processing, and in fact it doesn't support "1d" so I have to transform those to "1 day", etc.

also, the logs did not indicate any way that "1d" is a problem:

```
2023-01-13 12:00:33,151 DEBUG[requests_cache.policy.actions]:URL https://example.com matched pa
ttern "*": 1d
```

it should print the value it will actually use, and I would have expected louder crying about invalid values, exceptions, or at least logging with an error.

**Comment by JWCook** [comment]
Thanks for digging into that. You're right, that should raise an exception instead of quietly failing. I'll fix that.

There aren't any string values currently (intentionally) supported for `expire_after` or `urls_expire_after`, but the same function is used to parse httpdate values from response headers. The intent there was to ignore any malformed headers and fall back to default expiration values (not to cache forever).

**Comment by JWCook** [comment]
For parsing date/time expressions, I've tried most of the libraries out there in that category, and these are the two I'd recommend the most:
* [pytimeparse](https://github.com/wroberts/pytimeparse): Converts most common time expressions like '1d', '1 d', '1 day', '1d5h', etc. to `timedelta`
* [dateutil](https://dateutil.readthedocs.io) (if needed): Converts pretty much every known date/time string format to `datetime`

Those would be fun to add to requests-cache, but that's probably best left up to the user, to avoid adding extra dependencies most people won't need.

**Comment by JWCook** [comment]
Fixed in 0.9.8 and 1.0.0b1.

**Comment by glensc** [comment]
what about the second problem? if i change urls_expire_after policy, it would still read cache even (until it expires from there) the new time would say it is expired already?

**Comment by JWCook** [comment]
New expiration settings aren't retroactive, they will only apply to new responses saved to the cache. If changing your expiration is just a one-time or infrequent thing, you could use [BaseCache.reset_expiration()](https://requests-cache.readthedocs.io/en/stable/modules/requests_cache.backends.base.html#requests_cache.backends.base.BaseCache.reset_expiration).

That currently only takes a single `expire_after` value, though, not `urls_expire_after`. That's something I would be willing to add, though. If that would work for you, go ahead and create a new issue for that.

**Comment by JWCook** [comment]
Well, maybe that isn't exactly what you want, since that resets the expiration relative to the current time, not the original created date of each cached response. I suppose another keyword argument to change that behavior would also be possible.

**Comment by glensc** [comment]
I guess the current behavior mimics more real browsers, if the response is told to expire at N, then it's not even queried upstream if it has newer content.

**Comment by glensc** [comment]
the `expire_after` documentation is still confusing, the api doc shows `str` is allowed:
- https://requests-cache.readthedocs.io/en/stable/modules/requests_cache.backends.base.html#requests_cache.backends.base.BaseCache.reset_expiration

> expire_after ([Union](https://docs.python.org/3/library/typing.html#typing.Union)[[None](https://docs.python.org/3/library/constants.html#None), [int](https://docs.python.org/3/library/functions.html#int), [float](https://docs.python.org/3/library/functions.html#float), [str](https://docs.python.org/3/library/stdtypes.html#str), [datetime](https://docs.python.org/3/library/datetime.html#datetime.datetime), [timedelta](https://docs.python.org/3/library/datetime.html#datetime.timedelta)]) – New expiration value, relative to the current time

but the human readable block doesn't even mention `str`:
- https://requests-cache.readthedocs.io/en/stable/user_guide/expiration.html?highlight=expire_after#expiration-values

and why is there a `float`? microsecond granuality caching? :) not possible with HTTP headers. 

can api docs changed that every `expire_after` is also linked to `expiration.html#expiration-values`? maybe it be more helpful to developers?

**Comment by JWCook** [comment]
> the expire_after documentation is still confusing, the api doc shows str is allowed

It can still accept a valid httpdate string... but I don't know why anyone would want to do that. That's mostly just the result of using the same `ExpirationTime` type alias everywhere that expiration values are used. I'll remove `str` from the public function signatures, though.

> and why is there a `float`? 

Probably just because that's the type `datetime.timedelta()` accepts for its `seconds` value, and the type returned by `timedelta.total_seconds()`. But yeah, I can't think of a good reason to support microsecond resolution there. I'll probably remove that.

> can api docs changed that every `expire_after` is also linked to `expiration.html#expiration-values`  maybe it be more helpful to developers?

Sure, I'll add that.

Thanks for the suggestions!

**Comment by glensc** [comment]
FYI: went with `pytimeparse`:
- https://github.com/Taxel/PlexTraktSync/pull/1358

this is due library size difference:

```
➜ pip wheel --wheel-dir=wheels parsedatetime pytimeparse strtotime python-dateutil
Collecting parsedatetime
  Using cached parsedatetime-2.6-py3-none-any.whl (42 kB)
Collecting pytimeparse
  Using cached pytimeparse-1.1.8-py2.py3-none-any.whl (10.0 kB)
Collecting strtotime
  Using cached strtotime-1.0.4-cp311-cp311-macosx_13_0_arm64.whl
Collecting python-dateutil
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Saved ./wheels/parsedatetime-2.6-py3-none-any.whl
Saved ./wheels/pytimeparse-1.1.8-py2.py3-none-any.whl
Saved ./wheels/strtotime-1.0.4-cp311-cp311-macosx_13_0_arm64.whl
Saved ./wheels/python_dateutil-2.8.2-py2.py3-none-any.whl
Saved ./wheels/six-1.16.0-py2.py3-none-any.whl

➜ ls -lhS wheels
total 576K
-rw-r--r-- 1 glen staff 262K Jan 14 02:31 strtotime-1.0.4-cp311-cp311-macosx_13_0_arm64.whl
-rw-r--r-- 1 glen staff 242K Jan 14 02:31 python_dateutil-2.8.2-py2.py3-none-any.whl
-rw-r--r-- 1 glen staff  42K Jan 14 02:31 parsedatetime-2.6-py3-none-any.whl
-rw-r--r-- 1 glen staff  11K Jan 14 02:31 six-1.16.0-py2.py3-none-any.whl
-rw-r--r-- 1 glen staff 9.8K Jan 14 02:31 pytimeparse-1.1.8-py2.py3-none-any.whl
```

**Comment by glensc** [comment]
oh, so, setting `{ "*" : 0 }` doesn't disable caching of all requests:
- https://github.com/Taxel/PlexTraktSync/blob/53b87299f301e1c1c8dea1ab75128a6d07f1f03b/plextraktsync/factory.py#L88-L94

its an handler for application `--no-cache` flag.

is there a way to do it so on the instance?  i.e without global state or `with`-context?

**Comment by JWCook** [comment]
See #770
