### ISSUE TITLE
Cache-Control headers and default caching behavior

### ISSUE THREAD

**Issue by glensc** [requests-cache/requests-cache#769]
### The problem

I've got response having `Cache-Control: public, max-age=28800`

and if I inspect the cache item, it says `created: 2023-01-20 12:48:39 EET, expires: N/A (fresh)`

### Expected behavior

My understanding reading the documentation:
- https://requests-cache.readthedocs.io/en/stable/user_guide/headers.html?highlight=max-age#supported-headers

is that header is automatically understood and expires should be created+max-age.

### Steps to reproduce the behavior

<details><summary>test_request_cache_769.py</summary>

```py
#!/usr/bin/env python
import logging
from requests_cache import CachedSession, __version__ as cached_session_version
from importlib.metadata import version

url = f"https://api-v2launch.trakt.tv/shows/1390/seasons?extended=episodes"
urls_expire_after = {
    "example.com": 0,
}
session = CachedSession(
    urls_expire_after=urls_expire_after,
)

logging.basicConfig(level=logging.DEBUG, force=True)

print(f"cached_session version: {cached_session_version} ({version('requests_cache')})")

print(f"1. GET {url}")
response = session.get(url)
print(response)
print(type(response))

print(f"2. GET {url}")
response = session.get(url)
print(response)
print(type(response))

for name, value in response.headers.items():
    print(f"{name}: {value}")
```
</details>

<details open><summary>Output</summary>

```
➜ python test_request_cache_769.py
1. GET https://api-v2launch.trakt.tv/shows/1390/seasons?extended=episodes

DEBUG:requests_cache.policy.actions:Cache directives from request headers: {}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api-v2launch.trakt.tv:443
DEBUG:urllib3.connectionpool:https://api-v2launch.trakt.tv:443 "GET /shows/1390/seasons?extended=episodes HTTP/1.1" 200 None
DEBUG:requests_cache.session:Pre-cache checks for response from https://api-v2launch.trakt.tv/shows/1390/seasons?extended=episodes: {'disabled cache': False, 'disabled method': False, 'disabled status': False, 'disabled by filter': False, 'disabled by headers or expiration params': False}

<Response [200]>
<class 'requests.models.Response'>

2. GET https://api-v2launch.trakt.tv/shows/1390/seasons?extended=episodes
DEBUG:requests_cache.policy.actions:Cache directives from request headers: {}
request: GET https://api-v2launch.trakt.tv/shows/1390/seasons?extended=episodes, response: 200 (49.60 KiB), created: 2023-01-20 13:09:29 EET, expires: N/A (fresh)
<class 'requests_cache.models.response.CachedResponse'>
```
</details>

### Workarounds

_Is there an existing workaround for this issue?_

### Environment
- requests-cache version: 0.9.7, 1.0.0b1
- Python version: Irrelevant
- Platform: Irrelevant

**Comment by glensc** [comment]
Some more funny headers: `Cache-Control: max-age=0,stale-while-revalidate=86400`

Some description about it:
- https://web.dev/stale-while-revalidate/

> Browsers that don't support stale-while-revalidate will silently ignore that configuration value, and use [max-age](https://web.dev/http-cache/#versioned-urls), as I'll explain shortly…

```
➜ curl -i https://metadata.provider.plex.tv/
HTTP/2 200
date: Fri, 20 Jan 2023 11:17:18 GMT
content-type: application/xml; charset=utf-8
access-control-allow-origin: *
cache-control: max-age=0,stale-while-revalidate=86400
cdn-cache-control: max-age=86400
content-language: en
cross-origin-resource-policy: cross-origin
etag: W/"442-DDWuWd+WC7lM/D4F3pNScFnwlVw"
origin-agent-cluster: ?1
referrer-policy: no-referrer
strict-transport-security: max-age=31536000; includeSubDomains; preload
vary: Accept, Accept-Encoding, X-Plex-Language, X-Plex-Provider-Version
x-content-type-options: nosniff
x-dns-prefetch-control: off
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-plex-cache: bypass
x-plex-timestamp: 1666727958
x-plex-version: d8238f48e
x-xss-protection: 0
cf-cache-status: HIT
age: 17488
server: cloudflare
cf-ray: 78c767245940abed-TLL
```

**Comment by JWCook** [comment]
Using Cache-Control headers is an opt-in feature:
```python
session = CachedSession(cache_control=True)
```

It's not enabled by default because it would be an unexpected (and easy to miss) change in behavior for cases like web scraping, where you usually want a longer expiration and don't care about the server's recommendations.

**Comment by JWCook** [comment]
Also, `stale-while-revalidate` was implemented with #398 and #601, so you can test that out in the current beta release, if you want.

**Comment by pfmoore** [comment]
> Using Cache-Control headers to set expiration is an opt-in feature

I just hit this issue myself. I understand your logic, and I appreciate that changing defaults on a long-running project is an extremely tricky call to make. But would it be worth making this clearer in the documentation? I found this project by searching for "something that did caching for requests", and didn't look too closely into the details, simply copying the "getting started" examples. Either a visible warning at the top of the "quick start" section saying "if you want to respect the standard HTTP cache control headers, you need to set `cache_control=True` when creating the cached session" or simply including it in the examples, would be good.

Although I suddenly thought, would the httpbin.org example work with `cache_control=True`, as I bet that service doesn't set cache headers, for obvious reasons. And yet I tried it, and it does work (as in, it takes 1 second to do the loop). So is there something more going on here?

```
>>> r = session.get('http://httpbin.org/delay/1')
>>> r.headers
{'Date': 'Fri, 27 Jan 2023 16:48:16 GMT', 'Content-Type': 'application/json', 'Content-Length': '356', 'Connection': 'keep-alive', 'Server': 'gunicorn/19.9.0', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true'}
```

**Comment by JWCook** [comment]
Thanks for the feedback!

> Either a visible warning at the top of the "quick start" section saying "if you want to respect the standard HTTP cache control headers, you need to set cache_control=True when creating the cached session" or simply including it in the examples, would be good.

The [short list of features](https://github.com/requests-cache/requests-cache/blob/45e5184c171cc51c3bfba7d01bbe5342a3925609/README.md?plain=1#L22-L41) at the top does mention Cache-Control and links to docs about it, but you're right, that should be in the quickstart examples as well.

> Although I suddenly thought, would the httpbin.org example work with cache_control=True, as I bet that service doesn't set cache headers, for obvious reasons. And yet I tried it, and it does work (as in, it takes 1 second to do the loop). So is there something more going on here?

The default behavior is to cache with no expiration, i.e., store indefinitely unless you manually clear the cache ([more details here](https://requests-cache.readthedocs.io/en/main/user_guide/expiration.html)). That is different than how a browser would behave, which would usually be to set a heuristic expiration based on the current time compared to `Last-Modified`. That's something I would consider adding, so if you have any thoughts on that feel free to open another issue to discuss.

I'll update the quickstart examples to make those two points clearer. It can be tricky to figure out exactly the right amount of detail to include in the Readme, so any other feedback along those lines would be appreciated.

**Comment by JWCook** [comment]
Another tricky balance to get right is accommodating (at least) two fairly different audiences for whom "caching" comes with different expectations:
* Web scraping and testing: Usually more aggressive caching, with the expectation of "keep this stuff until I tell you not to"
* API clients and applications consuming an external service: Usually browser-like caching, with the expectation of "respect standard HTTP headers and balance performance with freshness"

Most caching libraries [like the ones listed here](https://requests-cache.readthedocs.io/en/main/project_info/related_projects.html) focus on either one or the other, so figuring out how to best communicate these different features sets in the docs is still a work in progress.

**Comment by JWCook** [comment]
I added a few more details and links to the Readme. Let me know if you have any other suggestions for improving that. Thanks!

**Comment by glensc** [comment]
Not much clear can you combine them or are they exclusive? and my interest is to use urls_expire_after and cache_control=True  together. of course trial and error would give the answer (or new bugreport :D), but maybe worth nothing it in docs as well.

**Comment by JWCook** [comment]
Yes, you can combine them. In that case, Cache-Control headers will always take precedence if they're available, and `expire_after` and/or `urls_expire_after` will be used when no cache headers are available.

The full list of precedence is documented here: https://requests-cache.readthedocs.io/en/stable/user_guide/expiration.html
