### ISSUE TITLE
Ability to store the `_content` value in plaintext instead of gzipped?

### ISSUE THREAD

**Issue by jayljohnson** [requests-cache/requests-cache#787]
I'd like to create a sqlite view on top of the `responses` table to parse out keys as columns from the `_content `key using the -> or ->> operators.  This will make it easier to do aggregate queries on the data like a sum() of one value from the payload across all of the responses for a time period.

Is there a way to store the `_content` values in plaintext so that the json can be parsed?  The api resposnse looks to be gzipped based on this:
![image](https://user-images.githubusercontent.com/7835211/218821153-0d587590-76ef-4cc0-8a83-2eccd5cefdc0.png)

and here's an example of the `_content` I'd like to see in json:
![image](https://user-images.githubusercontent.com/7835211/218820788-ca5f94b6-0977-44a4-83ab-143c032ce6d0.png)

Thanks!

**Comment by jayljohnson** [comment]
This seems to answer my questions: https://stackoverflow.com/questions/71539768/storing-response-as-json-in-python-requests-cache

Are there any other things to consider?

**Comment by JWCook** [comment]
In the next release, this will be the be the default behavior with the filesystem backend. See #631 for more details. There is a beta release on PyPI if you'd like to test it out.

**Comment by jayljohnson** [comment]
I tried using 1.0.0b1 with the following session configs, but the sqlite records don't have the field `_decoded_content`.  Is it only supported with the filesystem backend?

```
def get_session():
    session = CachedSession(
        'data/raw/http_cache',
        backend='sqlite',
        serializer='json',
        decode_content=True
    )
    return session
```

**Comment by JWCook** [comment]
That should work with any backend. Do you have some leftover responses cached with your previous settings, maybe?

Here's an example:
```python
import json
import sqlite3
from requests_cache import CachedSession

session = CachedSession(serializer='json', decode_content=True)
session.cache.clear()
r = session.get('http://httpbin.org/get')

with sqlite3.connect(session.cache.db_path) as con:
    result = con.execute('SELECT value FROM responses LIMIT 1').fetchone()

response_json = json.loads(result[0])
print(response_json['_decoded_content'])
```

**Comment by JWCook** [comment]
I'm going to close this for now, but let me know if you have any other questions.
