### ISSUE TITLE
`Cache-Control: must-revalidate` response header takes precedence over cache_control=False

### ISSUE THREAD

**Issue by jmaas-vector** [requests-cache/requests-cache#799]
### The problem
When using requests-cache against an API that sends cache directives (cache-control: max-age=0, private, must-revalidate), cache is always invalidated, neglecting the `cache_control` setting.

### Expected behavior
`cache_control=False` should lead to the cache being used, no matter what response headers are sent.

### Steps to reproduce the behavior
Use cache with API that sends the following headers: cache-control: max-age=0, private, must-revalidate
I observed this behaviour with the GitLab REST API.

### Workarounds
The `filter_fn` argument can be used to forge the response by removing the `cache-control` directives:
`response.headers.pop("cache-control")`

### Environment
- requests-cache version: 1.0.0
- Python version: 3.9.7
- Platform: Ubuntu 18.04

**Comment by JWCook** [comment]
Thanks for the bug report! I'll look into it.

**Comment by JWCook** [comment]
I found the issue. I just need to add some more tests, and double-check if there are any other headers that should be disabled by `cache_control=False` but currently aren't.

**Comment by jmaas-vector** [comment]
Awesome! Thanks for looking into the issue so quickly :)

**Comment by pembo13** [comment]
@JWCook is this fixed anywhere? Can I apply the fix to my local code? It's making requests_cache useless in a scenario I'm currently working with.

**Comment by pembo13** [comment]
Using the `filter_fn` workaround did not work for me. From what I can see, `_send_and_cache` is called before `filter_fn`

**Comment by JWCook** [comment]
Sorry for the delay. This has been fixed in 1.0.1. Give that a try and let me know if that resolves the issue for you.

**Comment by pembo13** [comment]
@JWCook thanks, looks good to me.
