### ISSUE TITLE
Cached response url: equals sign not escaped in paramater values

### ISSUE THREAD

**Issue by pjdewitte** [requests-cache/requests-cache#808]
### The problem
Since v1.0.0, an equals sign is not escaped in parameter values, in the url of a cached response. This seems to be an unintended change.

### Expected behavior
The url of a cached response should be equal to the url of the response that requests-cache returned earlier.

### Steps to reproduce the behavior
```
import sys
import requests
import requests_cache

print("Python", sys.version)
print("requests", requests.__version__)
print("requests_cache", requests_cache.__version__)


session = requests_cache.CachedSession(
    'test',
    backend='memory'
)

r = session.get(
    'https://google.com',
    params={'where': 'code=123'},
)
print(r.url, r.from_cache)

r = session.get(
    'https://google.com',
    params={'where': 'code=123'},
)
print(r.url, r.from_cache)
```
Output (1st correct, 2nd and 3rd incorrect):
```
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
requests 2.28.2
requests_cache 0.9.8
https://www.google.com/?where=code%3D123 False
https://www.google.com/?where=code%3D123 True

Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
requests 2.28.2
requests_cache 1.0.0
https://www.google.com/?where=code%3D123 False
https://www.google.com/?where=code=123 True

Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
requests 2.28.2
requests_cache 1.0.1
https://www.google.com/?where=code%3D123 False
https://www.google.com/?where=code=123 True

```

### Workarounds
N/A

### Environment
- requests-cache version: >=1.0.0
- Python version: verified on 3.9 and 3.10
- Platform: Windows

**Comment by JWCook** [comment]
Thanks for reporting that! I'll get that fixed soon.

**Comment by JWCook** [comment]
It turns out this is behavior from [url-normalize](https://github.com/niksite/url-normalize). I was about to create an issue, but it looks like it's already been reported: https://github.com/niksite/url-normalize/issues/25

This was introduced as part of redacting ignored parameters (e.g., credentials) from the cache. I split out the redaction step from the normalizing step so `CachedResponse.url` won't be affected.
