### ISSUE TITLE
Not multi threading ready?

### ISSUE THREAD

**Issue by softmarshmallow** [requests-cache/requests-cache#813]
My code breaks randomly after installing and running install_cache.

Id does not crashes immediately, randomly after few minutes, it crashes. I think it has something to do with multi threading and this packages of how it reads the local cache (It also fails with sqlite backend btw.)

How I use the cache
```
    install_cache(
      f'.cache/v{version}',
      backend='filesystem',
    )
```

And this is the crash I get randomly (No detailed info what so ever I can share.)
```
python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown                                                
  warnings.warn('resource_tracker: There appear to be %d ' 
```

Related
- https://github.com/conda/conda/issues/9589

**Comment by JWCook** [comment]
There's not enough info to tell what's causing that particular error message. Have you compared the behavior with and without requests-cache?

Regardless, `install-cache()` is not thread-safe, and there is more info about its limitations [here](https://requests-cache.readthedocs.io/en/stable/user_guide/general.html#patching-limitations-potential-issues).

Using `CachedSession` without patching, however, is thread-safe. And the filesystem backend is thread-safe, but not multiprocess-safe ([open issue for that here](https://github.com/requests-cache/requests-cache/issues/603), if/when it's needed). And there's more info on [choosing a backend here](https://requests-cache.readthedocs.io/en/stable/user_guide/backends.html#choosing-a-backend).

**Comment by JWCook** [comment]
I'm closing this for now, but let me know if you have any other questions.
