### ISSUE TITLE
Json list loading fails when loaded from cache

### ISSUE THREAD

**Issue by fvolchyok** [requests-cache/requests-cache#818]
### The problem
I'm trying to load and cache a json object with an array as a root. Initial "cold" loading from server works fine, but subsequent attempts to load the same request return seemingly good response but with empty content: `<CachedResponse [200]: created: 2023-04-28 09:58:37 +03, expires: N/A (fresh), size: 0 bytes, request: GET http://127.0.0.1:8000/list.json>`. `response.text` is empty, `response.json()` fails with error. The problem happens exactly on _loading_ from cache, not saving to. This can be confirmed by inspecting corresponding cache file (`_decoded_content` is fine there).

### Expected behavior
Response's content is not empty. List of objects is properly loaded. `response.text` is the original json string.

### Steps to reproduce the behavior

Setup a simple local server (in this instance I used `python3 -m http.server`) with two json files: 
- dict.json: `{"field": "value"}`
- list.json: `[1, 2, 3, 4, 5]`

```python
import requests
import requests_cache

requests_cache.install_cache(backend='filesystem')
requests_cache.clear()

# dict works fine
def load_dict():
    return requests.get('http://127.0.0.1:8000/dict.json')

assert load_dict().json()["field"] == "value"  # first actual load
assert load_dict().json()["field"] == "value"  # attempt to load value from cache


# list isn't loaded correctly
def load_list():
    return requests.get('http://127.0.0.1:8000/list.json')

assert load_list().json() == [1, 2, 3, 4, 5]  # first actual load, works fine since loaded directly from server
print(load_list())  # attempt to load list from cache, proof that response has no content
# <CachedResponse [200]: ..., size: 0 bytes, request: GET http://127.0.0.1:8000/list.json>

assert load_list().text != ""  # fails
assert load_list().json() == [1, 2, 3, 4, 5]  # raises exception on json parsing
```

### Workarounds
Currently I'm using this workaround in [`serializers/cattrs.py`](https://github.com/requests-cache/requests-cache/blob/main/requests_cache/serializers/cattrs.py), which is very ugly/inefficient and this problem definitely requires more consideration:

```diff
def _encode_content(response: CachedResponse) -> CachedResponse:
    """Re-encode response body if saved as JSON or text; has no effect for a binary response body"""
    if isinstance(response._decoded_content, str):
        response._content = response._decoded_content.encode('utf-8')
        response._decoded_content = None
        response.encoding = 'utf-8'  # Set encoding explicitly so requests doesn't have to guess
        response.headers['Content-Length'] = str(len(response._content))  # Size may have changed
+    elif isinstance(response._decoded_content, list) and "json" in response.headers["Content-type"]:
+        response._content = json.dumps(response._decoded_content).encode('utf-8')
+        response._decoded_content = None
+        response.encoding = 'utf-8'  # Set encoding explicitly so requests doesn't have to guess
+        response.headers['Content-Length'] = str(len(response._content))
    return response
```

### Environment
- requests-cache version: `1.0.1`
- Python version: `3.8.11`
- Platform: `macOS 13.2.1`

**Comment by JWCook** [comment]
Thank you for the detailed bug report! Your examples made this much easier to debug.

It looks like this was introduced in 1.0 (#647). The bug is in the [custom serialization hook](https://catt.rs/en/stable/structuring.html#registering-custom-structuring-hooks) here:
https://github.com/requests-cache/requests-cache/blob/e5d54b4f930956bbfdaf21d819e269a9857fc28a/requests_cache/serializers/cattrs.py#L112-L115

I'll fix that and add some better comments to that section.

**Comment by JWCook** [comment]
Fixes are in main. I'll get a patch release out sometime within the next couple weeks.
