### ISSUE TITLE
requests-cache is incompatible with urllib3 2.0

### ISSUE THREAD

**Issue by jpmckinney** [requests-cache/requests-cache#825]
`CachedHTTPResponse.from_response` does:

```
kwargs = {k: getattr(raw, k, None) for k in fields_dict(cls).keys()}
```

And one of the fields is `strict`, but `strict` was removed in urllib3 2.0.0.

`requests` dealt with this by removing `strict` from its code: https://github.com/psf/requests/compare/v2.29.0..v2.30.0#diff-490e3808e13126e458b69db19af4e6a408066311395c112cb8b3ef37445cd255

For now, a workaround is to pin to urllib3<2.

Related issue from another requests-based project: https://github.com/ionrock/cachecontrol/issues/292

**Comment by JWCook** [comment]
Thanks for the heads up. Looks like there's also one other incompatibility related to `HTTPResponse.read()` with `decode_content=True`.

```python
site-packages/urllib3/response.py:432: RuntimeError
RuntimeError: Calling read(decode_content=False) is not supported after read(decode_content=True) was called.
```

I'll get that fixed shortly.

**Comment by JWCook** [comment]
Fixed in main. This will be included in a patch release sometime within the next couple weeks.
