### ISSUE TITLE
No cache hits after calling `cache.recreate_keys`

### ISSUE THREAD

**Issue by mportesdev** [requests-cache/requests-cache#831]
### The problem
No cache hits after upgrading requests-cache from 0.9.8 to 1.0.1 and calling the `session.cache.recreate_keys()` method.

### Expected behavior
`recreate_keys()` would make previously cached responses reusable in the current version.

### Steps to reproduce the behavior

1. `pip install requests-cache==0.9.8`
2. Make some requests:

   ```python
   import requests_cache

   session = requests_cache.CachedSession()

   for url in (
       'https://www.volby.cz/opendata/prez2023/xml/perk.xml',
       'https://www.volby.cz/pls/prez2023/vysledky_kraj?kolo=1&nuts=CZ010',
       'https://www.volby.cz/pls/prez2023/vysledky_kraj?kolo=2&nuts=CZ010',
   ):
       response = session.get(url)
       print(response.from_cache, response.cache_key)
   ```

   Output:
   ```
   False 429de4a616434ff0
   False e29ed7cff14f5ea8
   False f3bba3a9c21f72cb
   ```

3. `pip install requests-cache==1.0.1`
4. Recreate the keys:

   ```python
   import requests_cache
   session = requests_cache.CachedSession()
   session.cache.recreate_keys()
   ```

   Check database contents:
   ```
   $ sqlite3 -header -column http_cache.sqlite 'select * from responses'
   key               value  expires
   ----------------  -----  -------
   c6d760d2c8662f37  ��
   ddf1a5b74bb3b36a  ����
   9cdd12e45c6517e3  ���\
   ```

   As expected - all the keys have changed.

5. Make the same requests as in step 2.

   Output:
   ```
   False 480cd5448f89ed57
   False 5d39231999fbd7fa
   False 6b272b1ecd346ee1
   ```

   Unexpected - three cache misses instead of three cache hits. Three new rows have been added to the database:

   ```
   $ sqlite3 -header -column http_cache.sqlite 'select * from responses'
   key               value  expires
   ----------------  -----  -------
   c6d760d2c8662f37  ��
   ddf1a5b74bb3b36a  ����
   9cdd12e45c6517e3  ���\
   480cd5448f89ed57  ��O
   5d39231999fbd7fa  ���
   6b272b1ecd346ee1  ��]
   ```

### Environment
- requests-cache version: 0.9.8 and 1.0.1
- Python version: 3.11.3
- Platform: Ubuntu 22.04

**Comment by mportesdev** [comment]
A request's body in version 0.9.8 is stored as `b'None'`, whereas in version 1.0.1 it is `b''`. This causes the difference in cache keys. It was already discussed [here](https://github.com/requests-cache/requests-cache/issues/678#issuecomment-1252665851).

**Comment by mportesdev** [comment]
This issue can be easily worked around by manually fixing the empty request bodies before `recreate_keys()` is called. For example:

```python
import requests_cache

def normalize_empty_bodies(cache):
    for key, response in list(cache.responses.items()):
        if response.request.body == b'None':
            response.request.body = b''
            cache.responses[key] = response

session = requests_cache.CachedSession()
normalize_empty_bodies(session.cache)
session.cache.recreate_keys()
```

**Comment by JWCook** [comment]
Thank you for the thorough bug report! I think that fix is simple enough that I'll go ahead and include that in `recreate_keys()`.

**Comment by JWCook** [comment]
Your example now works as expected, after changing step 3 to install from the current git repo:
```
pip install git+https://github.com/requests-cache/requests-cache
```

This will be included in the next release.
