### ISSUE TITLE
Cache Expiration : Example script not working 

### ISSUE THREAD

**Issue by sorasful** [requests-cache/requests-cache#851]
### The problem
I tried to run the `example/expiration.py` script and it doesn't work. 
We get an AssertionError : 

```
  File "C:\Users\expiration.py", line 34, in main
    assert not response.from_cache
AssertionError
```

### Expected behavior
The assertion to be right.

### Steps to reproduce the behavior
Just run the `example/expiration.py` script.

### Environment
- requests-cache version: requests-cache==1.1.0
- Python version: 3.10
- Platform: Windows 10

Thanks 👍

**Comment by JWCook** [comment]
Thanks for letting me know! The script hits https://httpbin.org, which appears to be having an outage right now (or unusually slow response times). If the problem persists, I'll update the example scripts to use a different test site.

**Comment by sorasful** [comment]
I don't think that https://httpbin.org/ is the problem. 
I also noticed the big slowdown of the website so I tried another website which was very fast and still got the issue. That's why I opened this ticket.

I was trying to implement the same behavior than in the script and it wouldn't work, so I figured out that I would try the script and I got the same behavior. 

Maybe there's really something there.

**Comment by JWCook** [comment]
I'm not able to reproduce this when running httpbin locally or using another test site.

> I was trying to implement the same behavior than in the script and it wouldn't work

Can you post your full example, and [enable debug logging](https://requests-cache.readthedocs.io/en/stable/user_guide/troubleshooting.html) and show me the output?

An example of a case where I'd expect this to behave differently is if the site supports [conditional requests](https://requests-cache.readthedocs.io/en/stable/user_guide/headers.html), in which case the server might respond with a 304. Then the cached response would be reused, and both `response.from_cache` and  `response.revalidated` would be True. In that case, the test could be changed to:
```py
assert response.revalidated or not response.from_cache
```

**Comment by sorasful** [comment]
You're right, seems like it's working now. That's weird.
I even tried again the previous version and it also worked. 

I'll try again on the environment where I first noticed this behavior to see if I still reproduce this. But I think I can close this and reopen it if needed.

Thanks for your time !
