### ISSUE TITLE
Feature request: Control Vacuum Rate

### ISSUE THREAD

**Issue by acbart** [requests-cache/requests-cache#852]
### Feature description

Currently, when you delete a request in the cache, the entire database is vacuumed. This makes sense - you want to clear out old data so that it's not actually taking up space. The issue is that the vacuuming happens after every deletion, even if I know that more deletions are on the way later. I'd like to have a way to disable the vacuum, even if it's only temporary. It'd be cool if I could specify "vacuum after N requests or B bytes or T seconds", but even just temporarily disabling it would be sufficient.

### Use case
Currently, I have a large cache file that has a few invalid ones. I can identify the invalid responses by retrying the request and inspecting the page, at which point I'll delete that request and retry the request. But each time I do this, the DB is vacuumed up and it takes like 10 seconds to do each one - for the hundred requests, this was a little painful :)

### Workarounds
Just being patient is sufficient. I suppose I could also have tried to do some monkey patching to temporarily stop the vacuuming behavior. But it seems like this should just be a parameter or configuration setting to say "don't vacuum for now".

### Plan to implement
I wish I had the time to do so, it seems like it'd be a pretty easy change. Unfortunately, I barely even had the free time to file this request!

**Comment by JWCook** [comment]
Sure, that makes sense. Here's what I can do:
* add an option `delete(
..., vacuum=False)`
* skip vacuuming by default if only deleting a single key

As a quick workaround, since you're deleting a single reaponse at a time, you can use the slightly lower-level dict-like interface available in `cache.responses`:
```py
key = response.cache_key
del session.cache.responses[key]

# later, if/when needed
session.cache.responses.vacuum()
```

Longer-term, SQLite has an incremental auto-vacuum feature that would probably be the best option for the use case you've described.

**Comment by JWCook** [comment]
@acbart These changes are in main, and will be included in the next release. Let me know if that looks good to you, and if the workaround I mentioned above works for you in the meantime.
