### ISSUE TITLE
Wrapping existing `requests.Session()`?

### ISSUE THREAD

**Issue by tazle** [requests-cache/requests-cache#858]
We have a library function that handles authentication and returns `requests.Session`. We would like to have caching behavior on the session, but leave the decision to the caller. Currently the only option to wrap such an existing session and give it caching behavior seems to be to "install" requests-cache, but this is clearly not ideal.

Am I missing some option to more selectively wrap an existing session to give it caching behaviour?

**Comment by JWCook** [comment]
Is this existing session object something that the user creates and passes to your library? If so, the user could create a `CachedSession` instead, and you could add an example of that to your docs.

Another option would be to create a new `CachedSession` and copy over all settings from the existing session (headers, cookies, auth, etc.).

It's also possible to modify the existing session object in-place and then manually initialize the `CachedSession`-specific parts, but it's possible that could break with future requests-cache versions (if init logic changes). I would consider adding something like that, with usage like:
```python
session = CachedSession.copy(user_session, **cache_settings)
```

**Comment by tazle** [comment]
The desired usage now is along the lines of
```
session = library.handle_authentication(...)
if we_are_dealing_exclusively_with_the_past:
  session = CachedSession.wrap(session, **cache_settings)
```

I suppose such wrapping `CachedSession` could work by using the underlying session as transport as long as the underlying session provides the session request methods and there's no interference through e.g. headers (which I wouldn't expect in this case).
