### ISSUE TITLE
Improve documentation of requests_cache.session.CachedSession

### ISSUE THREAD

**Issue by pavelsr** [requests-cache/requests-cache#867]
[Here](https://requests-cache.readthedocs.io/en/stable/modules/requests_cache.session.html#requests_cache.session.CachedSession) I think should be

> class requests_cache.session.CachedSession(cache_name='http_cache', backend=None, serializer=None, expire_after=-1, urls_expire_after=None, cache_control=False, allowable_codes=[200,], allowable_methods=['GET', 'HEAD'], always_revalidate=False, ignored_parameters=['Authorization', 'X-API-KEY', 'access_token', 'api_key'], match_headers=False, filter_fn=None, key_fn=None, stale_if_error=False, **kwargs)

instead of 

> class requests_cache.session.CachedSession(cache_name='http_cache', backend=None, serializer=None, expire_after=-1, urls_expire_after=None, cache_control=False, allowable_codes=(200,), allowable_methods=('GET', 'HEAD'), always_revalidate=False, ignored_parameters=('Authorization', 'X-API-KEY', 'access_token', 'api_key'), match_headers=False, filter_fn=None, key_fn=None, stale_if_error=False, **kwargs)

(array in `allowable_codes`, `allowable_methods` and `ignored_parameters` params instead of tuple)

I can't open merge request because I'm not sure which file to edit (seems like this part is auto-generated). Opened this issue to draw attention of maintainers to confusing docs.

**Comment by JWCook** [comment]
Tuple is the correct type for those defaults. Lists are mutable and shouldn't be used as parameter defaults.

You can pass any iterable, though (tuple, list, set, etc.), which you can see in the types listed under the 'Parameters' section:

![Screenshot_20230827_103423_Vivaldi Browser.jpg](https://github.com/requests-cache/requests-cache/assets/419936/e0b0dd16-8bac-4b12-b22b-46870a680020)

**Comment by JWCook** [comment]
I think this can be closed, but let me know if you have any other questions.
