### ISSUE TITLE
JSON body not decoded correctly when root element is a string (with JSON serializer, filesystem backend, and `decode_content=True`)

### ISSUE THREAD

**Issue by amangean** [requests-cache/requests-cache#868]
### The problem
Hi,
While using the `FileCache` backend I got a `JSONDecodeError` on `resp.json()` when retrieving a cached response which content is a string (like `"that"`, not having the same problem on _proper_ JSON object like `{"this": ...}`).
In the following code exposing the _bug_, said string displays as `'Douglas Adams'` (from `print(resp.text)`) when retrieved from the cache while it displays as `'"Douglas Adams"'` while not cached (there is some extra double quotes there).
I'm new to Python and new to `requests_cache` but this doesn't happen when using the SQLite backend in place of the `FileCache` backend (nor the `JSONDecodeError`, neither the double quotes disappearance thing) so I guess it's an actual bug.
Thanks for your work. :)

### Expected behavior
Have the exact same `resp` object wrt. the retrieved content whether it's been retrieved from cache or not (thus no `JSONDecodeError`).

### Steps to reproduce the behavior
I tried to make a _minimal reproducible example_:
```py
import requests_cache
from requests.exceptions import JSONDecodeError

if __name__ == "__main__":

  session = requests_cache.CachedSession("requests_cache", backend="filesystem")

  url = "https://www.wikidata.org/w/rest.php/wikibase/v0/entities/items/Q42/labels/en"
  request = requests_cache.Request("GET", url).prepare()

  # Making sure the response won't be retrieved from cache the first time
  cache_key = session.cache.create_key(request)
  session.cache.delete(cache_key)

  def send():
    resp = session.send(request)
    print(f"{resp.from_cache=}")
    print(f"{resp.text=}")
    
    try: resp.json()
    except JSONDecodeError:
      print(":(")

  send()
  send()
```

Output:
```
resp.from_cache=False
resp.text='"Douglas Adams"'
resp.from_cache=True
resp.text='Douglas Adams'
:(
```

### Workarounds
Even if `"Douglas Adams"` isn't a _proper_ JSON object, `json.loads('"Douglas Adams"')` returns `'Douglas Adams'` while `json.loads('Douglas Adams')` (no double quotes) raises a `json.decoder.JSONDecodeError` exception so I guess some code in the `FileCache` backend make these double quotes not being stored in the cache object.

### Environment
- requests-cache version: 1.1.0
- Python version: 3.11.3
- Platform: Arch Linux

**Comment by JWCook** [comment]
Thanks for the bug report. It looks like the problem is that a response body won't be correctly decoded as JSON unless the root element is an object or array (python dict or list). A later version of JSON specification ([RFC 7159](https://datatracker.ietf.org/doc/html/rfc7159#section-2)) allows the root element to be basically anything (object, array, number, string, bool, or null). So the response in your example is actually valid JSON. I'll plan on fixing that in the next release.

Meanwhile, a workaround you can use is to set `decoded_content=False` to store the original binary response body instead of the decoded JSON body. Example:
```py
import requests_cache

session = requests_cache.CachedSession(backend="filesystem", decode_content=False)
session.cache.clear()

url = "https://www.wikidata.org/w/rest.php/wikibase/v0/entities/items/Q42/labels/en"
r1 = session.get(url)
r2 = session.get(url)
assert r1.json() == r2.json()
```

**Comment by JWCook** [comment]
Fixes for this are now in main and will be included in the next release.
