### ISSUE TITLE
Problems with streamed responses

### ISSUE THREAD

**Issue by netomi** [requests-cache/requests-cache#893]
Since update of v1.1.0 I noticed some problems with streamed requests.

My request code:

```
            response = self.requester.request_raw("GET", f"/repos/{org_id}/{repo_name}/zipball/{ref}", stream=True)
            for chunk in response.iter_content(chunk_size=8192):
                file.write(chunk)
```

I use a CachedSession with conditional requests.

This leads to an exception like that:

```
<Response [200]>
<class 'requests_cache.models.response.OriginalResponse'>

Traceback (most recent call last):
  File "/home/tn/workspace/eclipse/otterdog/otterdog/cli.py", line 495, in _execute_operation
    exit_code = max(exit_code, operation.execute(org_config))
  File "/home/tn/workspace/eclipse/otterdog/otterdog/operations/sync_template_operation.py", line 70, in execute
    updated_files = rest_api.repo.sync_from_template_repository(
  File "/home/tn/workspace/eclipse/otterdog/otterdog/providers/github/rest/repo_client.py", line 904, in sync_from_template_repository
    self._download_repository_archive(archive_file, template_owner, template_repo)
  File "/home/tn/workspace/eclipse/otterdog/otterdog/providers/github/rest/repo_client.py", line 944, in _download_repository_archive
    for chunk in response.iter_content(chunk_size=8192):
  File "/home/tn/workspace/eclipse/otterdog/.venv/lib/python3.10/site-packages/requests/models.py", line 835, in iter_content
    if self._content_consumed and isinstance(self._content, bool):
AttributeError: 'OriginalResponse' object has no attribute '_content_consumed'

```

When I force a refresh, this problem goes away. It looks like the OriginalResponse object that wraps the Response, does not have such a _content_consumed property. I see that the CacheResponse has a version of that property that always returns true.

It could be that when trying to do a conditional request with stream enabled, the server does not return 304 and thus a different code path is used:

```
        if not actions.skip_write:
            self.cache.save_response(response, actions.cache_key, actions.expires)
        elif cached_response is not None and response.status_code == 304:
            cached_response = actions.update_revalidated_response(response, cached_response)
            if not actions.skip_write:
                self.cache.save_response(cached_response, actions.cache_key, actions.expires)
            return cached_response
        else:
            logger.debug(f'Skipping cache write for URL: {request.url}')
        return OriginalResponse.wrap_response(response, actions)
```

so if a 304 is returned a cached response is returned, otherwise the wrapped OriginalResponse. If I specify force refresh True, the problem goes away.

**Comment by JWCook** [comment]
Thanks for the bug report. That attribute is supposed to have been set in [`requests.Response.__init__()`](https://github.com/psf/requests/blob/839a8edec37c81a18ac8332cfbd44f44e1ae6206/src/requests/models.py#L660) before being wrapped by `OriginalResponse`.

I'm not sure yet why that's happening, but it should be easy enough to fix.

**Comment by netomi** [comment]
I am not 100 percent sure why it happens, will try to compile a test case. It happens when accessing the api from GitHub to download an archive of a repository with stream enabled.

Atm I use force refresh to circumvent the problem. I have not noticed with a previous version of the cache, only since I updated to the latest version but that might be a concidence.

**Comment by netomi** [comment]
Ok so this test fails after the response has been cached in a filesystem cache.
Strangely, if I run the test a second time, it still works, but from the third time on it fails consistently with the error as above. So something weird is going on that I will need to dig further into it.

```
from requests_cache import CachedSession
from tempfile import TemporaryFile


def test():
    session = CachedSession(
            "test",
            backend="filesystem",
            use_cache_dir=False,
            cache_control=True,
            allowable_methods=["GET"],
        )

    headers = {
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "X-Github-Next-Global-ID": "1",
    }

    response = session.request(
            "GET",
            url="http://api.github.com/repos/requests-cache/requests-cache/zipball/main",
            headers=headers,
            refresh=True,
            stream=True,
        )

    with TemporaryFile() as file:
        for chunk in response.iter_content(chunk_size=8192):
            file.write(chunk)

```

**Comment by netomi** [comment]
I do believe its due to relocations. The url that is requested is relocated to some other url.
At some point in the _send_and_cache method we receive a CachedResponse that we try to wrap in an OriginalResponse class which then leads to the problem. If I change the code to the following:

```
        if isinstance(response, CachedResponse):
            return response
        else:
            return OriginalResponse.wrap_response(response, actions)

```

the problem goes away.

**Comment by JWCook** [comment]
Thanks for looking into this. So the more general case of this is when a request results in a cache miss, but the same request with updated headers results in a cache hit. That isn't something I expected, but it makes sense after looking at your example with the GitHub API.

Specifically, this is a corner case with:
* streaming requests
* conditional requests
* response redirects that change based on validation status

In this case, when the remote content has changed (200 response instead of 304) GitHub will redirect the request from `api.github.com` to `codeload.github.com`.

**Comment by netomi** [comment]
Initially I thought its related to an update of the requests-cache library but I guess it was just a concidence and I tested it with older versions and triggered the same behavior. GitHub must have added a redirect for that API call that resulted in that behavior as it was working perfectly for a couple of months before.

Ty for fixing this.
