### ISSUE TITLE
Feature request: Add session option to always refresh

### ISSUE THREAD

**Issue by dseomn** [requests-cache/requests-cache#899]
### Feature description

I'd like a session option like `always_revalidate`, but with the functionality of the request option `refresh`.

### Use case
I have a client for Wikidata, and I generally want to cache responses for 20 hours since the data generally doesn't change frequently. But if the user just edited the data on Wikidata and knows it changed, I'd like to have a flag they can pass to my software to refresh every request to Wikidata. (Some of the requests are complex queries, so it's not easy to figure out which requests could be affected by the user's change.)

### Workarounds

I could pass the `refresh` option to every request.

### Plan to implement

I'm not currently interested in working on a PR, but I might be in the future. Not sure.

**Comment by dseomn** [comment]
I think I found a much easier workaround, so I'm not sure how much value there is in this feature request anymore.

```
session.headers["Cache-Control"] = "no-cache"
```

**Comment by JWCook** [comment]
Right, requests-cache will respect `no-cache` and [other request headers](https://requests-cache.readthedocs.io/en/stable/user_guide/headers.html#supported-headers). I think either that or passing `refresh` to individual requests makes more sense than a new keyword argument for `CachedSession`.

> Some of the requests are complex queries, so it's not easy to figure out which requests could be affected by the user's change.

That is an interesting case. I don't know enough about the Wikidata API to have any useful suggestions there, but if you do figure out the relevant request parameters to look for, you could iterate over `session.cache.responses` (or [filter()](https://requests-cache.readthedocs.io/en/stable/modules/requests_cache.backends.base.html#requests_cache.backends.base.BaseCache.filter)), check each response, and [delete()](https://requests-cache.readthedocs.io/en/stable/modules/requests_cache.backends.base.html#requests_cache.backends.base.BaseCache.delete) any that match your criteria.
