### ISSUE TITLE
`stream=True`: IncompleteRead(50440 bytes read, -25220 more expected)

### ISSUE THREAD

**Issue by nschloe** [requests-cache/requests-cache#910]
The following stream-to-extract request succeeds with `requests`, but fails with `requests-cache`:

```python
import requests
import tarfile

import requests_cache

url = "https://arxiv.org/e-print/1102.00510v1"

# works:
# r = requests.get(url, timeout=10, stream=True)

# doesn't:
cached_session = requests_cache.CachedSession()
r = cached_session.get(url, timeout=10, stream=True)


with tarfile.open(fileobj=r.raw) as tar:
    tar.extractall(path="/tmp")
```

The error message is

```python
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(50440 bytes read, -25220 more expected)', IncompleteRead(50440 bytes read, -25220 more expected))
```

Unrelated to https://github.com/requests-cache/requests-cache/issues/878.

**Comment by JWCook** [comment]
Thanks for the bug report. I can reproduce this locally and a somewhat ugly workaround is possible, but I haven't yet figured it out. The `IncompleteRead` error seems to be related to the difference in size between the encoded (in this case gzipped) and decoded content. I haven't seen this happen with any other streaming requests, though. Do you happen to have any insight into anything special that arxiv.org might be doing with its streamed responses?

I see the response content headers for this request look like:
```py
Content-Encoding: x-gzip
Content-Type: application/x-eprint-tar
```

`Content-Encoding: x-gzip` is documented in RFC 9110 and handled by `urllib3`, so no issues there. I'm not familiar with `Content-Type: application/x-eprint-tar`, though, and can't seem to find any docs about it. What exactly is `application/x-eprint-tar`?

**Comment by JWCook** [comment]
Also to explain the step in requests-cache that's currently failing:
* Read raw response content so it can be saved to the cache
* Store raw response content on `response.raw` (`urllib3.HTTPResponse` object) and reset file pointers so `response.iter_content()` behaves like the original response for streaming usage
  *  In other words, "read response content but pretend like it hasn't been read yet." This is the main part that's different from default `requests` behavior.
* Store decoded content in `response._content` (for direct/non-streaming usage)

**Comment by nschloe** [comment]
> What exactly is `application/x-eprint-tar`?

They explain their media types [here](https://info.arxiv.org/help/mimetypes.html). Not sure how relevant this is though. My idea of `requests-cache` has been that it should emulate `requests` as closely as possible, even for exotic or incorrect requests.

**Comment by JWCook** [comment]
>  it should emulate `requests` as closely as possible, even for exotic or incorrect requests.

Yes, that's the goal. But to make that happen, there are some special cases that need to be explicitly handled, and this could be one of them. I'm just trying to understand what might be different about this particular request compared to other streaming requests.

**Comment by hellupline** [comment]
I created a minimal setup to test this bug, but I couldnt isolate if it was the gzip compression causing the error:

minimal nginx setup with gzip support:

```nginx.conf
server {
    listen [::]:80 default_server;
    listen 80 default_server;
    server_name _;
    expires 30d;
    slice 1m;
    server_tokens off;
    gzip on;
    gzip_types video/webm plain/text;
    gzip_min_length 10;
    location / {
        gzip on;
        alias /usr/share/nginx/html/;
    }
}
```

start it with :

```bash
docker run --rm -it \
  -v "${PWD}/default.conf:/etc/nginx/conf.d/default.conf" \
  -v "${PWD}/large_file.webm:/usr/share/nginx/html/large_file.webm" \
  -w /usr/share/nginx/html \
  -p 80:80 \
  nginx:latest
```

and test compression using:

```bash
curl http://localhost:80/large_file.webm --silent --output /dev/null --write-out "%{size_download}\n"
curl http://localhost:80/large_file.webm --silent --output /dev/null --write-out "%{size_download}\n" -H "Accept-Encoding: gzip,deflate"
```

and the minimal python script:

```python3
from io import BytesIO
from requests_cache import CachedSession
from requests import Session
url = "http://localhost:80/large_file.webm"
chunk_size = 1024
buffer = BytesIO()
with CachedSession() as session:
    response = session.request(
        method="GET",
        url=url,
        stream=True,
        headers={"accept-encoding": "identity"},
    )
    total_size = int(response.headers.get("content-length", 0))
    # for chunk in response.iter_content(chunk_size=chunk_size):
    #     buffer.write(chunk)
    for chunk in response.raw.stream(chunk_size, decode_content=False):
        buffer.write(chunk)
    buffer.seek(0)
    print(len(buffer.getvalue()))
```

in python I explicity disabled gzip compression, and still receive the incorrect chunk size error

**Comment by JWCook** [comment]
Big thanks to @deeenes for fixing this (#958)! I'll make a new release for this soon.

This one was hard to track down, but it seems that it was just a matter of resetting some internal urllib3 counts both before _and_ after reading response content. Otherwise its counts can get out of sync during chunked reads (streaming requests), and it complains when it doesn't match the expected amount of total bytes read based on the `Content-Length` header.

This example now works as expected:
```py
import tarfile
import requests_cache

session = requests_cache.CachedSession()
r = session.get('https://arxiv.org/e-print/1102.00510v1', timeout=10, stream=True)
with tarfile.open(fileobj=r.raw) as tar:
    tar.extractall(path='/tmp')
```

**Comment by deeenes** [comment]
Great, thanks @JWCook!
