### ISSUE TITLE
1.1.1: documentation build fails

### ISSUE THREAD

**Issue by kloczek** [requests-cache/requests-cache#918]
```console
+ /usr/bin/python3 -sBm build -w --no-isolation
* Getting build dependencies for wheel...
* Building wheel...
fatal: not a git repository (or any parent up to mount point /home/tkloczko)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Successfully built requests_cache-1.1.1-py3-none-any.whl
+ PBR_VERSION=1.1.1
+ PDM_BUILD_SCM_VERSION=1.1.1
+ SETUPTOOLS_SCM_PRETEND_VERSION=1.1.1
++ ls -1 /home/tkloczko/rpmbuild/BUILD/requests-cache-1.1.1/dist/requests_cache-1.1.1-py3-none-any.whl
+ JARACO_PACKAGING_SPHINX_WHEEL=/home/tkloczko/rpmbuild/BUILD/requests-cache-1.1.1/dist/requests_cache-1.1.1-py3-none-any.whl
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v7.1.2

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 356, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/tkloczko/rpmbuild/BUILD/requests-cache-1.1.1/docs/conf.py", line 20, in <module>
    from requests_cache import __version__  # noqa: E402
  File "/home/tkloczko/rpmbuild/BUILD/requests-cache-1.1.1/requests_cache/__init__.py", line 7, in <module>
    from .backends import *
  File "/home/tkloczko/rpmbuild/BUILD/requests-cache-1.1.1/requests_cache/backends/__init__.py", line 7, in <module>
    from .base import BaseCache, BaseStorage, DictStorage
  File "/home/tkloczko/rpmbuild/BUILD/requests-cache-1.1.1/requests_cache/backends/base.py", line 20, in <module>
    from ..models import AnyRequest, CachedResponse
  File "/home/tkloczko/rpmbuild/BUILD/requests-cache-1.1.1/requests_cache/models/__init__.py", line 7, in <module>
    from .base import RichMixin
  File "/home/tkloczko/rpmbuild/BUILD/requests-cache-1.1.1/requests_cache/models/base.py", line 4, in <module>
    from attr import Factory
ImportError: cannot import name 'Factory' from 'attr' (/usr/lib/python3.8/site-packages/attr.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 285, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 207, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 179, in read
    namespace = eval_config_file(filename, tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 369, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 356, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/tkloczko/rpmbuild/BUILD/requests-cache-1.1.1/docs/conf.py", line 20, in <module>
    from requests_cache import __version__  # noqa: E402
  File "/home/tkloczko/rpmbuild/BUILD/requests-cache-1.1.1/requests_cache/__init__.py", line 7, in <module>
    from .backends import *
  File "/home/tkloczko/rpmbuild/BUILD/requests-cache-1.1.1/requests_cache/backends/__init__.py", line 7, in <module>
    from .base import BaseCache, BaseStorage, DictStorage
  File "/home/tkloczko/rpmbuild/BUILD/requests-cache-1.1.1/requests_cache/backends/base.py", line 20, in <module>
    from ..models import AnyRequest, CachedResponse
  File "/home/tkloczko/rpmbuild/BUILD/requests-cache-1.1.1/requests_cache/models/__init__.py", line 7, in <module>
    from .base import RichMixin
  File "/home/tkloczko/rpmbuild/BUILD/requests-cache-1.1.1/requests_cache/models/base.py", line 4, in <module>
    from attr import Factory
ImportError: cannot import name 'Factory' from 'attr' (/usr/lib/python3.8/site-packages/attr.py)


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 356, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/tkloczko/rpmbuild/BUILD/requests-cache-1.1.1/docs/conf.py", line 20, in <module>
    from requests_cache import __version__  # noqa: E402
  File "/home/tkloczko/rpmbuild/BUILD/requests-cache-1.1.1/requests_cache/__init__.py", line 7, in <module>
    from .backends import *
  File "/home/tkloczko/rpmbuild/BUILD/requests-cache-1.1.1/requests_cache/backends/__init__.py", line 7, in <module>
    from .base import BaseCache, BaseStorage, DictStorage
  File "/home/tkloczko/rpmbuild/BUILD/requests-cache-1.1.1/requests_cache/backends/base.py", line 20, in <module>
    from ..models import AnyRequest, CachedResponse
  File "/home/tkloczko/rpmbuild/BUILD/requests-cache-1.1.1/requests_cache/models/__init__.py", line 7, in <module>
    from .base import RichMixin
  File "/home/tkloczko/rpmbuild/BUILD/requests-cache-1.1.1/requests_cache/models/base.py", line 4, in <module>
    from attr import Factory
ImportError: cannot import name 'Factory' from 'attr' (/usr/lib/python3.8/site-packages/attr.py)
```
I'm using `attr` 0.3.2.

**Comment by JWCook** [comment]
Looks like that's a different library ([attr](https://github.com/denis-ryzhkov/attr) vs [attrs](https://github.com/python-attrs/attrs)). The `attrs` library has both namespaces, so I can see that's a bit confusing. I just updated that to make it clearer (#920).

There are some more details on project setup in [CONTRIBUTING.md](https://github.com/requests-cache/requests-cache/blob/main/CONTRIBUTING.md). You can also find the [documentation-specific dependencies here](https://github.com/requests-cache/requests-cache/blob/main/pyproject.toml#L56-L66), which can be installed along with all the other project dependencies with:
```sh
poetry install -E all -E docs
```

Just curious, in what kind of build environment are you seeing this traceback? Is this in a downstream package build?

**Comment by kloczek** [comment]
Looking on https://github.com/requests-cache/requests-cache/compare/v1.1.1...main I think that it would be good to flush all those commits and release new version.
Do you have any plans to do that soon?

Also it would be good to restart create gh releases.
On create github release entry is created email notification to those whom have set in your repo the web UI Watch->Releases.
gh release can contain additional comments (li changelog) or additional assets like release tar balls (by default it contains only assets from git tag) however all those part are not obligatory.
In simplest variant gh release can be empty because subiekt of the sent email contains git tag name.

I'm asking because my automation process uses those email notifications by trying to make preliminary automated upgrades of building packages, which allows saving some time on maintaining packaging procedures.
Probably other people may be interested to be instantly informed about release new version as well.

Documentation and examples of generate gh releases:
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://cli.github.com/manual/gh_release_upload/
https://github.com/jbms/sphinx-immaterial/pull/282
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/
https://github.com/jbms/sphinx-immaterial/issues/281#issuecomment-1700933026
tox target to publish on pypi and make gh release https://github.com/jaraco/skeleton/blob/928e9a86d61d3a660948bcba7689f90216cc8243/tox.ini#L42-L58

**Comment by kloczek** [comment]
> ```shell
> poetry install -E all -E docs
> ```

Such requirements does not make any sense in case of packaging any general package management software.

**Comment by JWCook** [comment]
Currently, I create GitHub releases only for major and minor releases, and the intended audience for those is "general users who mainly just care about high-level release highlights." In other words, I'm using it for documentation and not automation, which is a fairly common use case.

For automated systems, the source of truth for new releases is git tags and PyPI, and that's sufficient for all downstream builds that I'm currently aware of. For example, [conda-forge builds](https://github.com/conda-forge/requests-cache-feedstock) are triggered from PyPI releases, and [AUR packages](https://aur.archlinux.org/packages/python-requests-cache) are based on git tags.

To be more specific, here are options for getting notified:
* git tags
    * If you don't have an existing tool to watch a git repo for tags, https://newreleases.io and https://release-monitoring.org are a couple options.
    * Aside: I do wish GitHub offered a Watch option to subscribe to just tags. Looks like there is a thread about that here, but that probably won't happen anytime soon: https://github.com/dear-github/dear-github/issues/399
* PyPI ([RSS feed here](https://pypi.org/rss/project/requests-cache/releases.xml))

Hope that helps.

>  I think that it would be good to flush all those commits and release new version. Do you have any plans to do that soon?

Yes, but I don't have a specific release date set.

> Such requirements does not make any sense in case of packaging any general package management software.

Then you will need to provide some context for what you are trying to accomplish.

**Comment by kloczek** [comment]
- pypi is only for python modules
- cannot find on https://newreleases.io/ or https://release-monitoring.org/ list of monitored projects
- is it any problem with opening yet another channel of spreading information about new release by for example plug create gh release under gh workflow like it is in provided example? 🤔

**Comment by JWCook** [comment]
> pypi is only for python modules

Yes, and this is a python module, so you can get its release information from PyPI. You will need to provide some context to explain why this isn't suitable for your needs.

> cannot find on https://newreleases.io or https://release-monitoring.org

https://release-monitoring.org/project/19752/
https://newreleases.io/github/requests-cache/requests-cache

> is it any problem with opening yet another channel of spreading information about new release

Yes, because it's not "opening another channel," it's changing an existing one. I am already using GitHub releases for general users who typically only care about important (major + minor) releases, not as something for automated systems to rely on.

I could be persuaded to change that, but you will need to put in at least a little effort to research the options you already have available and make a more compelling case for why this change is worthwhile.

**Comment by kloczek** [comment]
> Yes, because it's not "opening another channel," it's changing an existing one. I am already using GitHub releases for general users who typically only care about important (major + minor) releases, not as something for automated systems to rely on.

Nope .. gh release is not changing anything.
By create gh release ONLY causes spreading notifications over email.

Nevertheless this is kind of side topic.
Because it is not possible apply attr->atrrs fix on top of the last release I'm more interested about possibility to release new version with that fix.

**Comment by JWCook** [comment]
[This change](https://github.com/requests-cache/requests-cache/pull/920) was just cosmetic; it's still using the same library. The only fix you need is to install [attrs](https://github.com/python-attrs/attrs). More info on why it has two namespaces can be found [here](https://www.attrs.org/en/stable/names.html). It looks like the package you have installed is [attr](https://pypi.org/project/attr/), a separate and unrelated library.
