### ISSUE TITLE
JSON content not decoded

### ISSUE THREAD

**Issue by lacombar** [requests-cache/requests-cache#927]
### The problem
JSON content is not decoded if `Content-Type` is only a partial valid match 

### Expected behavior
JSON content is decoded.

### Steps to reproduce the behavior
Server responding with `Content-Type` to `application/json; charset=utf-8`

### Workarounds
Override the response via serializer chain to set `Content-Type` to `application/json`

### Environment
- requests-cache version: 1.1.1
- Python version: 3.8.10
- Platform: Windows 10

**Comment by JWCook** [comment]
Thanks for the bug report. That should be an easy fix.
