### ISSUE TITLE
Would be helpful if the Requsets-Ratelimiter example mentioned argument order

### ISSUE THREAD

**Issue by nk9** [requests-cache/requests-cache#931]
Thanks very much for your super easy-to-use requests tools! 😄 I had a minor setback just now and wanted to suggest an improvement.

### The problem
I adapted the cache/ratelimiter example and tried to use it, but it failed with the following stack:

```
  File "source.py", line 52, in scrape
    self.session = CachedLimiterSession(

  File "requests_cache/session.py", line 79, in __init__
    super().__init__(**get_valid_kwargs(super().__init__, kwargs))  # type: ignore

  File "requests_ratelimiter/requests_ratelimiter.py", line 60, in __init__
    self.limiter = limiter or Limiter(

  File "pyrate_limiter/limiter.py", line 34, in __init__
    self._validate_rate_list(rates)

  File "pyrate_limiter/limiter.py", line 51, in _validate_rate_list
    raise InvalidParams("Rate(s) must be provided")
```

### Steps to reproduce the behavior
```
from requests import Session
from requests_cache import CacheMixin
from requests_ratelimiter import LimiterMixin


class CachedLimiterSession(CacheMixin, LimiterMixin, Session):
    """Session class with caching and rate-limiting behavior. Accepts arguments for both
    LimiterSession and CachedSession.
    """

session = CachedLimiterSession("http_cache", 
    per_second=5,
    allowable_codes=[200],
    allowable_methods=["GET", "HEAD", "POST"]
)
```

### Workarounds
The problem was that I had put the requests-ratelimiter argument _before_ the requests-cache arguments. I can see now why that happened, but still: it's not every day most people work with Mixins, and this took a bit to resolve. A sentence in the example about that would be helpful.

**Comment by JWCook** [comment]
Good suggestion, thanks! I'll add a note about that to the docs.

With mixins, the best option is to avoid positional args if possible. In this case, all arguments for both [CacheMixin](https://requests-cache.readthedocs.io/en/stable/modules/requests_cache.session.html) and [LimiterMixin](https://requests-ratelimiter.readthedocs.io/en/stable/reference.html) can be passed as keyword arguments, so they can be passed in any order:
```py
from requests import Session
from requests_cache import CacheMixin
from requests_ratelimiter import LimiterMixin

class CachedLimiterSession(CacheMixin, LimiterMixin, Session):
    """Session class with caching and rate-limiting behavior. Accepts arguments for both
    LimiterSession and CachedSession.
    """

session = CachedLimiterSession(
    cache_name="http_cache", 
    per_second=5,
    allowable_codes=[200],
    allowable_methods=["GET", "HEAD", "POST"]
)
```

**Comment by nk9** [comment]
That's great, thanks!
