### ISSUE TITLE
requests-cache/1.2.0: tests failures during debian build

### ISSUE THREAD

**Issue by sandrotosi** [requests-cache/requests-cache#971]
Hello,
im preparing requests-cache/1.2.0 for inclusion in Debian, and as part of our process, we run tests after the build step. Some of them are failing:

```
FAILED tests/unit/test_base_cache.py::test_delete__expired - AssertionError: assert 3 == 1
FAILED tests/unit/test_base_cache.py::test_delete__expired__per_request - AssertionError: assert 3 == 2
FAILED tests/unit/test_base_cache.py::test_delete__older_than - AssertionError: assert 4 == 3
FAILED tests/unit/test_session.py::test_expired_request_error - Failed: DID NOT RAISE <class 'ValueError'>
FAILED tests/unit/test_session.py::test_stale_if_error__exception - AssertionError: assert (True is True and False is True)
FAILED tests/unit/test_session.py::test_stale_if_error__error_code - AssertionError: assert False is True
FAILED tests/unit/test_session.py::test_stale_if_error__error_code_in_allowable_codes - AssertionError: assert 200 == 404
FAILED tests/unit/test_session.py::test_request_expire_after__enable_expiration - AssertionError: assert True is False
FAILED tests/unit/test_session.py::test_request_expire_after__prepared_request - AssertionError: assert True is False
FAILED tests/unit/test_session.py::test_request_only_if_cached__expired - AssertionError: assert 200 == 504
FAILED tests/unit/test_session.py::test_request_only_if_cached__stale_if_error__expired - AssertionError: assert False is True
```

the full build log, with the detailed tracebacks is here (at the very bottom): 
[python-requests-cache_1.2.0-1_amd64.build.txt](https://github.com/requests-cache/requests-cache/files/14549183/python-requests-cache_1.2.0-1_amd64.build.txt)

btw the failures happen both with python 3.11 and 3.12

**Comment by JWCook** [comment]
It looks like these are all tests that involve timing. They could potentially fail if they are running on an especially slow machine or VM. I can't fix that, but what I could do on this end is add a pytest marker that would allow you to skip all the timing-related tests.

**Comment by JWCook** [comment]
A dependency issue could be possible, assuming you're not installing them with the poetry lockfile. You could compare your dependencies against the version constraints in [pyproject.toml](https://github.com/requests-cache/requests-cache/blob/main/pyproject.toml), and look at the [GitHub Actions config](https://github.com/requests-cache/requests-cache/blob/main/.github/workflows/build.yml) for other clues about environment differences.

[time-machine](https://github.com/adamchainz/time-machine) is used for all of these failed tests for mocking system time, so that's the first thing I'd check.

**Comment by sandrotosi** [comment]
@JWCook i see you marked this ticket closed as completed, did you do something to address this issue?

**Comment by JWCook** [comment]
As far as I can tell, this isn't something I can reproduce or address on this end. If there is something you want to change about the tests, I would happily accept a PR for it.
