### ISSUE TITLE
expires_unix is not giving consistent results

### ISSUE THREAD

**Issue by glensc** [requests-cache/requests-cache#975]
### The problem

I was exploring cache contents and found something odd, `r.expires_unix` fluctuates 1s between different runs on same data.

```py
    for r in session.cache.responses.values():
        print(f"{r.expires_unix}: {r.url}")
```

different outcome from different runs:
```
➜ grep 'https://api.trakt.tv/shows/134421/seasons?extended=episodes' /tmp/cache[456]
/tmp/cache4:1710720658: https://api.trakt.tv/shows/134421/seasons?extended=episodes
/tmp/cache5:1710720659: https://api.trakt.tv/shows/134421/seasons?extended=episodes
/tmp/cache6:1710720658: https://api.trakt.tv/shows/134421/seasons?extended=episodes
```

### Expected behavior

It should be `1710720658` or `1710720659` on every run.

### Environment
- requests-cache version: 1.2.0

**Comment by JWCook** [comment]
It looks like the current method for converting to a unix timestamp introduces a bit of randomness based on the delta from the current time and rounding the `microseconds` value to the nearest second. I can fix that.
