### ISSUE TITLE
urls_expire_after and url query string filtering

### ISSUE THREAD

**Issue by glensc** [requests-cache/requests-cache#977]
I noticed that urls stored to cache get their query string arguments sorted.

But what about `urls_expire_after` patterns? are they applied after or before sorting?

for example, application making such requests:

```py
        "metadata.provider.plex.tv/library/search?query=*&searchTypes=movies&includeMetadata=1": "1h",
```

**Comment by JWCook** [comment]
Expiration patterns are checked against the original request URL you provide, not the normalized URL that's stored in the cache.
