### ISSUE TITLE
How should I disable caching for testing?

### ISSUE THREAD

**Issue by stfnx** [requests-cache/requests-cache#979]
Hi,
I've a base class that inherits from `requests_cache.CacheMixin` and `requests.Session` and sets a default cache lifetime `expire_after=NEVER_EXPIRE`.

Then I have another class that inherits from this base client. One method sets `expire_after=598` explicitly for a request.

For testing I want to disable caching, but passing `expire_after=NEVER_EXPIRE` to my test client instance does not work, because the per-request option has precedence.

So how am I supposed to:
1. Set a default cache lifetime for my class that is used 99% of the time.
2. Use a different cache lifetime for some requests.
3. Then disable caching for my tests.

**Comment by JWCook** [comment]
The easiest way to disable caching is by mocking the `CacheMixin` class and replacing it with a regular `requests.Session` (or if you want, another custom subclass of Session to use for testing). There's an example of doing that here: https://requests-cache.readthedocs.io/en/stable/user_guide/compatibility.html#disabling-requests-cache

Let me know if that accomplishes what you want.

**Comment by stfnx** [comment]
Hi. This does work for me:

```py
@pytest.fixture(scope='function')
def requests_cache_mock(requests_mock):
    with requests_cache.disabled():
        yield requests_mock
```

But now I have the problem that my logger tries to access `response.from_cache` and `response.expires` which don't exist in this case. The cleanest solution would be if I could just pass a `expire_after=DO_NOT_CACHE`, but I guess that's not possible.

Anyway, thanks for your help! :)

**Comment by stfnx** [comment]
Nope, I was wrong. This does not work. It still writes to cache.
The other solution from the documentation doesn't work either.

My class is inheriting from `CacheMixin`. So I tried the following without success:
```py
@pytest.fixture(scope='function', autouse=True)
def disable_requests_cache():
    with mock.patch('requests_cache.CacheMixin'):
        yield
```

Could I just clear the cache before each test? I guess that would work for my current situation.

**Comment by stfnx** [comment]
Seems like replacing the `SQLite` backend with `memory` did work for me...

**Comment by JWCook** [comment]
Sure, using the memory backend is a valid option too.

If patching the session class or mixin didn't work, post your custom session class definition and I can help debug.
