### ISSUE TITLE
Remove bson from pyproject.toml.

### ISSUE THREAD

**Issue by caseyclements** [requests-cache/requests-cache#999]
### The problem

The [PyMongo Installation docs](https://pymongo.readthedocs.io/en/latest/installation.html) clearly states "Do not install the “bson” package from pypi. PyMongo comes with its own bson package; doing “pip install bson” or “easy_install bson” installs a third-party package that is incompatible with PyMongo."

 The bson package in pypi has not been updated in pypi since 2020. Any environment containing both bson and pymongo is likely to break.

### Expected behavior

A one-line change. Any requirement from the extra bson dependency will be achieved by installing the mongodb extra instead.

### Steps to reproduce the behavior
A simple example that demonstrates how bson has gone out-of-date.
```
docker run -it --rm python:3.11 bash
pip install bson
python -c "from bson.errors import InvalidId"
```

**Comment by JWCook** [comment]
That is intended as an option to use BSON as a standalone codec without pymongo/MongoDB, for example with the filesystem backend: https://requests-cache.readthedocs.io/en/stable/user_guide/serializers.html#bson-serializer

The lack of maintenance on that repo is a good point, though. Are there specific unaddressed bugs that you're aware of? Or is your concern accidentally installing it at the same time as pymongo?

**Comment by caseyclements** [comment]
Yes, the issue arises when one has pymongo and bson in the same environment.

**Comment by caseyclements** [comment]
Opened PR #1000

**Comment by ShaneHarvey** [comment]
(Another pymongo maintainer here) Currently any app that uses requests_cache's "bson" extra is unable to use pymongo because the two are incompatible.

> That is intended as an option to use BSON as a standalone codec without pymongo/MongoDB

It is fine to use BSON without MongoDB but we still recommend installing pymongo because it provides the official bson package: https://pymongo.readthedocs.io/en/latest/api/bson/index.html

**Comment by JWCook** [comment]
Alright, point taken. Thanks for the feedback. And thanks for your work on pymongo and motor!
